### ISSUE TITLE
PIC 16F1459 RB7 pin wrong on DIP and SOIC variants

### ISSUE THREAD

**Issue by rpfand** [KiCad/kicad-library#1005]
PIC 16(L)F1459 - I/SS, I/P and I/ST have RB7/TX/CK as PIN 7. Should be PIN 10. Verified with Microchip datasheet 40001629b.pdf at http://ww1.microchip.com/downloads/en/DeviceDoc/40001639B.pdf .

**Comment by SchrodingersGat** [comment]
@rpfand thanks for pointing this out - can you make a Pull Request with the required fixes?

**Comment by rpfand** [comment]
I'll take care of it today. Thanks for putting this repo together.

**Comment by SchrodingersGat** [comment]
Fixed in https://github.com/KiCad/kicad-library/pull/1007
