### ISSUE TITLE
Note more strictly that prefered length of pins is 100mil 

### ISSUE THREAD

**Issue by Fat-Zer** [KiCad/kicad-library#101]
KiCad_Library_Convention
> 3.2. Pin has a length of 100mil or more in increments of 50mil if number needs more space.

IMO It would be nice to mark it down more strictly that the pins should be 100mil and shouldn't be increased unless it's really required. The current text may be confused with «100mil or any higher value with 50 mil increment on your taste».

**Comment by CarlPoirier** [comment]
Hi,

I'm taking note. I will write a new revision soon and will include your suggestion.

**Comment by nickoe** [comment]
Also one should conisder the pin length might not nessesarely align with 50 mil, if the other end ( the one without the circle) should align to some "diagonal" graphic line as in the case of the triangle on the op amps. So the requirement basically is the the wire point should align with the grid.

**Comment by CarlPoirier** [comment]
Fixed in the latest KLC revision.
