### ISSUE TITLE
Where to put shield footprints?

### ISSUE THREAD

**Issue by svheymann** [KiCad/kicad-library#1026]
Is there a footprint lib for stuff like this i am just working on:
![grafik](https://cloud.githubusercontent.com/assets/25146520/23134832/8740a544-f796-11e6-863d-3cf1c30ba1dc.png)

or eg Arduino/Raspi shields?

Thanks!

**Comment by jkriege2** [comment]
I would say there are two options:
1. You add a project template:
2. You add the actual (micro)controller board as a part that can be mounted on the lowe-side or upper-side of the PCB, see my current PR for Arduino: https://github.com/KiCad/Modules.pretty/pull/3

Best,
JAN

**Comment by svheymann** [comment]
Hmm. What i try to have in the end is a symbol with multiple parts (for each pin header) like this:
![grafik](https://cloud.githubusercontent.com/assets/25146520/23154480/50e8e16e-f80e-11e6-8477-e2e2f3e9d02e.png)

Where all the signal names are already in place like this in eagle:

![grafik](https://cloud.githubusercontent.com/assets/25146520/23154514/833d5e92-f80e-11e6-826c-66bceb730cf0.png)

And when you add one of the connectors the footprint (or part of it, or you can delete the parts you dont need?) for this shield appears in the netlist/pcbnew.

I would find it more intuitive if a shield would be a "part" in the kicad-lib that you can simply add like a normal connector but with multiple sub-parts?

That would have the advantage if you like to add one of the connectorparts later in the design process you could do that using the lib symbol or am i wrong?

**Comment by jkriege2** [comment]
Then, what I proposed in 2) is what you want to do ... whether the Symbol is split or not is a different Story (and I think Splitting should be OK here).

Best,
JAN

**Comment by svheymann** [comment]
Do i understand that correctly, i should add the positive footprint (upper side of the board)?
So that someone can move the needed connectors (provided by the symbol) to the correct position on the lower side of the (negative) shield and then delete the board footprint?

**Comment by jkriege2** [comment]
The footprint should contain all connectors ... If you want variants where only 2 of 5 connectors are present you should make several varying footprints with names describing that ... but I don't really see the sense in that ...

**Comment by svheymann** [comment]
Ok. The PR i referenced adds the board with all connectors on which the shield can be mounted.

**Comment by svheymann** [comment]
I splitted the 5 connectors to 5 different symbols in one lib. Now you can choose which connectors you use on the shield board and move it to the correct position using the board template in the PR. The symbols look like this:

![grafik](https://cloud.githubusercontent.com/assets/25146520/24222675/2245863a-0f53-11e7-8887-4eaf70497d50.png)

In which lib would this fit in or should i create a new olimex lib?

**Comment by jkriege2** [comment]
Maybe `modules.lib`... but I'm not sure about that ...

**Comment by svheymann** [comment]
I put the new symbols into a PR.
