### ISSUE TITLE
Duplicated MMBT3906?

### ISSUE THREAD

**Issue by yhlien** [KiCad/kicad-library#1074]
Is there anybody experiencing a warning like "duplicated MMBT3906 symbol in transistor library"?

**Comment by jkriege2** [comment]
did you update to the current kicad-library master? Is the problem still there (I tried to fix some problems in transistors.lib a few days ago)?

**Comment by yhlien** [comment]
Yes, I did.  It is still there. I try to open the transistors.lib and find MMBT3906 is also an alias of BC807. I guess that is the origin of the issue...

**Comment by jkriege2** [comment]
this should solve it: https://github.com/KiCad/kicad-library/pull/1075

**Comment by yhlien** [comment]
Unfortunately, the same symptom for IRF540N...
