### ISSUE TITLE
Library 'transistors' has duplicate name entry

### ISSUE THREAD

**Issue by Marsfan** [KiCad/kicad-library#1089]
I just started getting this. I tried uninstalling kicad, and pulling the github repo again. Apparently the transistors library has duplicate name entries for these components:

BC850
BC849
BC856
BC857
BC858
BF244A
BF244B
BF244C
IRF540N

![capture](https://cloud.githubusercontent.com/assets/9311953/23625043/66d5a930-026d-11e7-9fb7-7111376c79f3.PNG)

**Comment by SchrodingersGat** [comment]
@Marsfan this is fixed here - https://github.com/KiCad/kicad-library/pull/1078 - which is waiting on - https://github.com/KiCad/kicad-library/pull/1076

**Comment by SchrodingersGat** [comment]
Thanks for raising this issue, though :)
