### ISSUE TITLE
move 3d model from unused to relay through hole

### ISSUE THREAD

**Issue by andres53016** [KiCad/kicad-library#109]
This 3d models are in the folder unused_3d:
./Relay_ThroughHole_Packages.relay_Finder_34Point51Point7.wings
./Relay_ThroughHole_Packages.Relay_SPDS_OMRON-G6E.wrl
./Relay_ThroughHole_Packages.RELAY_SANYOU_SRD_Series_Form_C.wings
./Relay_ThroughHole_Packages.relay_Finder_34Point51.wrl
./Relay_ThroughHole_Packages.RELAY_SANYOU_SRD_Series_Form_C.wrl
./Relay_ThroughHole_Packages.Relay_SPDS_OMRON-G6E.wings
./Relay_ThroughHole_Packages.relay_Finder_34Point51.wings
./Relay_ThroughHole_Packages.relay_Finder_34Point51Point7.wrl
and the respective footprint are in https://github.com/KiCad/Relays_ThroughHole.pretty, how I can fix this.

**Comment by michal777** [comment]
There was some broken links, eg. Relay_SANYOU_SRD_Series_Form_C.kicad_mod lost its 3d model with commit: https://github.com/KiCad/Relays_ThroughHole.pretty/commit/25d6fb88be865b4e6ba77ea21eaaa3cbeeb7eb7f

If you want to fix it, please move the 3d models to kicad-library/modules/packages3d/Relays_ThroughHole/ then rename these .wings/.wrl files to match names of footprints and add relative links to footprints in footprint editor (set proper scale, offset, rotation if necessary).

Before renaming 3d models it would be good to rename footprints (name and reference):
Relays->Relay; Relais->Relay; bistabil->bistable

**Comment by andres53016** [comment]
thanks, I create the pull requests

**Comment by CarlPoirier** [comment]
Corresponding pull request is #110

**Comment by CarlPoirier** [comment]
This got fixed.
