### ISSUE TITLE
请问如何通过FREECAD软件输出3D模型？

### ISSUE THREAD

**Issue by Xduino** [KiCad/kicad-library#1091]
你好！我自己用设计的后缀名为STEP的3D模型，用FREECAD输出WRL 2.0，可以在KICAD中显示，但是网上下载的一些STEP后缀文件，输出后无法显示。

**Comment by jkriege2** [comment]
Could you ask your question in English please?

Best,
JAN

**Comment by Xduino** [comment]
How do I output 3D model FREECAD and then import KiCad?
Hello there! I use the design of the suffix named STEP 3D model, with FREECAD output WRL 2.0, can be displayed in the KICAD, but the Internet to download some of the STEP suffix file, output can not be displayed.

**Comment by Xduino** [comment]
@jkriege2 How do I output 3D model FREECAD and then import KiCad?
HI! I use the design of the suffix named STEP 3D model, with FREECAD output WRL 2.0, can be displayed in the KICAD, but the Internet to download some of the STEP suffix file, output can not be displayed. Thank U！

**Comment by jkriege2** [comment]
@easyw Could you comment on that?

**Comment by easyw** [comment]
@Xduino 
the easiest way to do it is through [KiCad StepUp](https://sourceforge.net/projects/kicadstepup/)
you can follow a [howto video](https://youtu.be/O6vr8QFnYGw)
and get some tips at KiCad forum
[how-to-interactive-align-3d-model-to-pcbnew-footprint-new-tool-for-kicad-in-altium-style](https://forum.kicad.info/t/how-to-interactive-align-3d-model-to-pcbnew-footprint-new-tool-for-kicad-in-altium-style/1711)
Recently many 3D STEP models have been merged in to the [official 3D MCAD repo](https://github.com/KiCad/packages3D)
If you need further assistance you can find me  KiCad Forum
Cheers,
Maurice

**Comment by Xduino** [comment]
@easyw Hi！ Will "kicad StepUp tool" how to install the freecad toolbar above it? thanks！
![Uploading 无标题.jpg…]()

**Comment by easyw** [comment]
as in the kicadStepUp-starter-Guide.pdf @ pg7
http://www.freecadweb.org/wiki/Customize_Toolbars

**Comment by Shackmeister** [comment]
@Xduino Hello, in case you got the answers you needed can you please consider closing this issue?

**Comment by Shackmeister** [comment]
@Xduino hi, ill close this now, if you want you can reopen it
