### ISSUE TITLE
Error when starting CvtPCB

### ISSUE THREAD

**Issue by sidprice** [KiCad/kicad-library#1096]
Errors were encountered loading footprints:
PARSE_ERROR: Expecting 'circle, rectangle, oval, or trapezoid' in input/source 'https://github.com/KiCad/Connectors.pretty' line 34 offset 14 from C:/Jenkins/workspace/windows-kicad-msys2-stable/src/kicad/common/dsnlexer.cpp : Expecting() : line 369
Sid

**Comment by poeschlr** [comment]
We already know about it.
Someone added a footprint with a rounded rectangle to the library. Sorry about that. (Hopefully one of the maintainers will do something about this.)
https://github.com/KiCad/Connectors.pretty/issues/66

**Comment by jkriege2** [comment]
fix is merged: https://github.com/KiCad/Connectors.pretty/pull/68

**Comment by sidprice** [comment]
Excellent ... thanks.
