### ISSUE TITLE
KLC: why the silkscreen width has become 0.12mm instead 0.15mm?

### ISSUE THREAD

**Issue by eldarkg** [KiCad/kicad-library#1108]
My pcb manufacturer required use the minimal silkscreen width 0.15mm

**Comment by SchrodingersGat** [comment]
0.12mm is the nominal recommended silkscreen width as per IPC-7351C, the latest industry standard. 

In the new KLC (https://github.com/SchrodingersGat/kicad-library/wiki/KLC) 0.12 or 0.15mm are allowed

**Comment by SchrodingersGat** [comment]
You can change the width to 0.15mm for all items in the PCB using a text-editor or script if your fab needs 0.15mm

**Comment by eldarkg** [comment]
@SchrodingersGat ok. I understand you
