### ISSUE TITLE
Body diode backwards on BSS138 et al.

### ISSUE THREAD

**Issue by horvathp** [KiCad/kicad-library#1123]
I believe the body diode is drawn with opposite polarity on the transistors.lib/BSS138 (2N7002 etc.) model. 
https://www.fairchildsemi.com/datasheets/BS/BSS138.pdf
On a side note, there are generic MOS/NPN/PNP etc. transistors in device.lib with different pin arrangements. I think it would make sense having generic NMOS/PMOS with body diode in device.lib as well.

**Comment by horvathp** [comment]
Furthermore, BSS138 has aliases
TP0610T and VP0610T.
However, these are P-Channel, is BSS138 N-Channel. 
Isn't this a mistake?

**Comment by cpavlina** [comment]
Yeah, you're correct, it's backward, and the aliases are a mistake.

**Comment by SchrodingersGat** [comment]
@horvathp thanks for pointing this out - could you perhaps submit a PR fixing this issue?

**Comment by jkriege2** [comment]
@horvathp a side-note: The NMOS/PMOS in device.lib do HAVE a body diode ... a fix of transistors.lib would be great!

**Comment by horvathp** [comment]
Indeed they have, I was looking at an older version.

**Comment by SchrodingersGat** [comment]
Fixed in https://github.com/KiCad/kicad-library/pull/1135
