### ISSUE TITLE
Question about courtyard

### ISSUE THREAD

**Issue by hackscribble** [KiCad/kicad-library#1138]
Rule 7.5.iv says of the courtyard:

> Clearance is measured from exterior of pads and package outline

For an SMD package such as the one in the image, should the courtyard be the smallest bounding rectangle that satisfies the clearance distance, or should it be a polygon that is narrower around the pins (since the distance between outer pins is narrower than the body)?

Thanks.

![image](https://cloud.githubusercontent.com/assets/7076027/24608132/1255fa02-186d-11e7-9855-87a1a30e535b.png)

**Comment by gauravjuvekar** [comment]
Courtyard is intended to allow space for machine-placing of components or for manual access while soldering by hand.
In your posted image, courtyard should be a rectangle.
However, exceptions can be made in case of eg a sufficiently large weirdly shaped component, where keeping it as a rectangle would waste significant board space.

**Comment by hackscribble** [comment]
Thanks, @gauravjuvekar
