### ISSUE TITLE
3D Module Scaling Errors

### ISSUE THREAD

**Issue by stambaughw** [KiCad/kicad-library#115]
The following 3D models require scaling to fit properly on the board:

SMD_Packages/SOT-23-6.wrl
SMD_Packages/SOT-23-5.wrl
SMD_Packages/SOIC-14_N.wrl
Diodes_SMD/Diode-SMA_Standard.wrl

I'm sure there are others as well.  I think it's important for our user's that they not have to rescale the 3D models to fit their boards.

Thanks,

Wayne

**Comment by CarlPoirier** [comment]
There is a similar issue on Github. I flagge these as well. No one had
gotten to it, but I'll try soon.

**Comment by stambaughw** [comment]
No hurry.  I just would like to have this cleaned up by the next stable
release which hopefully will be around the June/July time frame.

**Comment by CarlPoirier** [comment]
Can someone double check SMD_Packages/SOIC-14_N and Diodes_SMD/Diode-SMA_Standard? Both seem fine on my end. I did fix the SOT-23*.

**Comment by stambaughw** [comment]
On 2/22/2015 9:43 PM, CarlPoirier wrote:
> Can someone double check SMD_Packages/SOIC-14_N and
> Diodes_SMD/Diode-SMA_Standard? Both seem fine on my end. I did fix the
> SOT-23*.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KiCad/kicad-library/issues/115#issuecomment-75482359>.
> 
Attached are screen shots of the attached 3d model.  One is scaled to
1/2.54cm and on is unscaled (1).  Both are incorrect AFAICT.  I just did
a git pull and reinstall yesterday unless I did something wrong.

**Comment by keruseykaryu** [comment]
I didn't check that recently, but does this issue is still up to date for SOIC-14_N?
https://github.com/KiCad/kicad-library/issues/49

**Comment by CarlPoirier** [comment]
I'm sorry Wayne but everything seems fine here. Github plugin activated, kicad-library on master. I don't see your screenshots, so let me upload one.

![image](https://cloud.githubusercontent.com/assets/5577772/6362321/d8905518-bc59-11e4-868c-55fdcf595fe6.png)

SOIC-14_N is alright as well.

**Comment by stambaughw** [comment]
On 2/24/2015 7:21 PM, CarlPoirier wrote:
> I'm sorry Wayne but everything seems fine here. Github plugin activated,
> kicad-library on master. I don't see your screenshots, so let me upload one.
> 
> image
> <https://cloud.githubusercontent.com/assets/5577772/6362321/d8905518-bc59-11e4-868c-55fdcf595fe6.png>
> 
> SOIC-14_N is alright as well.
> 
> �
> Reply to this email directly or view it on GitHub
> <https://github.com/KiCad/kicad-library/issues/115#issuecomment-75880579>.
> 
I just did a fresh clone using:

git clone https://github.com/KiCad/kicad-library.git

Then I changed the 3D package absolute path to point directly at
SMD_Packages/SOIC-14_N.wrl rather than using CMake to install and I
still get the same thing.  You haven't done a local checkout on your
branch and forgot to merge the changes into the master branch have you?
 Please send me a copy of your SOIC-14_N.wrl file so I can do a diff.

**Comment by CarlPoirier** [comment]
No, I did a fresh clone as well! I don't understand either what's
happening. I'll send you the ,wrl and .kicad_mod files for the SOIC-14_N on
your personal email.

**Comment by CarlPoirier** [comment]
The issue has been confirmed to not exist anymore with the most recent revision of kicad-library and the latest footprints.
