### ISSUE TITLE
Footprint filters for conn_??x?? symbols are very restricted should they include more footprints?

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-library#1170]
We have a lot of footprints for different connectors. But the conn_??x?? symbols have only pin headers and socket strips in their footprint filters.
Any suggestions how the footprint filters should look like? 
Should we add all applicable footprints manually or is there a better option?

**Comment by SchrodingersGat** [comment]
This behaviour is in nightly only but it would pay to make use of this for 5.0.x

**Comment by poeschlr** [comment]
How does the stable version react if there is a ":" character in one of the footprint filters?

**Comment by SchrodingersGat** [comment]
It tries to match it just against the footprint and fails

**Comment by SchrodingersGat** [comment]
It was exactly for the use case that you describe here that I implemented this filter feature :)

**Comment by poeschlr** [comment]
Thanks  for implementing this feature and for the clarification.
If nobody else volunteers i would add this filters to the conn_ symbols. But i probably will not be able to do it before the end of may.

**Comment by SchrodingersGat** [comment]
Should be easy enough to fix with a handy text editor and some regex :)

**Comment by poeschlr** [comment]
@SchrodingersGat What nightly version did add this feature? I would like to test this but i think my nightly might be a bit too old. (I might need to update my operating system to get updates again.)

**Comment by evanshultz** [comment]
@poeschlr Can this be closed now?
