### ISSUE TITLE
SMD relay repo

### ISSUE THREAD

**Issue by jkriege2** [KiCad/kicad-library#1177]
Hi @SchrodingersGat 

could you please generate a new repo https://github.com/KiCad/Relays_SMD.pretty to complement https://github.com/KiCad/Relays_THT.pretty ... 

Best,
JAN

**Comment by SchrodingersGat** [comment]
Jan,

Repo is [here](https://github.com/KiCad/Relays_SMD.pretty) - linked with Travis too.

Also here is a [PR](https://github.com/KiCad/kicad-library/pull/1181) to add this to the library table.

**Comment by jkriege2** [comment]
Thanks,
JAN
