### ISSUE TITLE
Audio Library LM1875 3d package file missing

### ISSUE THREAD

**Issue by davidsrsb** [KiCad/kicad-library#1190]
The LM1875 symbol calls TO_SOT_Packages_THT.3dshapes/TO-220-5_Pentawatt_Multiwatt-5_Vertical_StaggeredType1.wrl
This does not exist in the library.
There are Pentawatt packages, which have spelling errors eg "verical" and don't look like their naming meets KLC standards

**Comment by maqifrnswa** [comment]
Hi - check out https://github.com/KiCad/kicad-library/pull/1212 for models
