### ISSUE TITLE
ESP support in KiCad

### ISSUE THREAD

**Issue by ChristianHirsch** [KiCad/kicad-library#1248]
@SchrodingersGat Is there specific reason why none of the [ESP boards](http://www.esp8266.com/wiki/doku.php?id=esp8266-module-family) are available in KiCad?

**Comment by furieuxjk** [comment]
What about this library? https://github.com/jdunmire/kicad-ESP8266

**Comment by jkriege2** [comment]
because nobody contributed the symbols and footprints yet. We would be happy to accept such symbols+footprint though ;-)

Best,
JAN

**Comment by SchrodingersGat** [comment]
We would happily accept submission of footprints / symbols / 3D models for these devices

**Comment by SchrodingersGat** [comment]
@ChristianHirsch if you want to contribute the ESP boards then you are more than welcome! I will close this issue for now. Thanks.
