### ISSUE TITLE
MAX31855 thermocouple-to-digital converter: duplicate symbols

### ISSUE THREAD

**Issue by hackscribble** [KiCad/kicad-library#1271]
`sensors.lib` has MAX31855 ...

![image](https://cloud.githubusercontent.com/assets/7076027/26578280/16f5fdbe-4527-11e7-871a-49b7f0f2269a.png)

`interface.lib` has MAX31855KASA plus aliases for other suffixes ...

![image](https://cloud.githubusercontent.com/assets/7076027/26578365/7db0c106-4527-11e7-96d4-dffd57abb806.png)

If the librarians think this should be rationalised, I'm happy to raise a PR.  Also noticed that the MAX31820 temperature sensor (plus aliases) is in `maxim.lib` not `sensor.lib`.

**Comment by jkriege2** [comment]
If you have time: Go ahead and submit a PR with the changes. I would suggest using the symbol from interface.lib, but maybe moving the footprint field to the bottom right, besides the GND-pin. The symbol in sensors.lib can then be removed (it's more like an interface, as it connects toa thermocouple but does not contain one itself). You could also move those temp-sensors from maxim.lib to sensors.lib.

Best & Thanks,
JAN

**Comment by hackscribble** [comment]
Thanks @jkriege2 I'll work on it this week.

**Comment by hackscribble** [comment]
Closed by https://github.com/KiCad/kicad-library/pull/1595
