### ISSUE TITLE
KLC-modifications for graphical symbols/power-symbols

### ISSUE THREAD

**Issue by jkriege2** [KiCad/kicad-library#1287]
Dear all (and @SchrodingersGat ):

as discussed earlier, I'm proposing here some changes to KLC to allow for graphical and power-flag symbols. This PR is accompagniied by changes to the KLC-check-scripts: https://github.com/KiCad/kicad-library-utils/pull/126

## graphical symbols (no pins, hidden REF, not in BOM)
These require:
- hidden REFDES
- REFDES with leading '#'
- may have no FPFilter and footprint
- may have hidden VALUE field, which causes the symbol name to have a leading tilde '~' (this is not stated explicitly in KLC, as it is an internal "Hack" of KiCAD, but the scripts should know about this!)

## power-flag symbols (1 pin, hidden REF, not in BOM, visible value)
These require:
- hidden REFDES is always `#PWR`
- may have no FPFilter and footprint
- VALUE field is visible
- may have only one pin
- pin signal name is the same as the symbol name

## required changes:

KLC 4.9.i should be changed to:
> The Reference field contains the appropriate Reference Designator (REFDES) and is _visible_. For power-flag symbols (e.g. `+5V`, `GND`, ...), the reference designator is always `#PWR`. For graphical symbols (no pins, not part of the BOM) the REFDES is _invisible_ and arbitrary, but starts with a hash-character `#` (e.g. `#SYM` or `#LOGO`).

KLC 4.9.ii should be changed to:
> The Value field contains the name of the symbol and is _visible_. For graphical (no pins, not part of the BOM) and power-flag symbols the value field may also be _invisible_.

please add to KLC 4.11:
> 4.11.vi For power-flag and graphical symbols, no footprint filter is required and the footprint field should be empty

add KLC 4.13:
> 4.13 Power-flag symbols
>  4.13.i power-flag symbols have a reference designator `#PWR` (cf. KLC 4.9.i)
>  4.13.ii power-flag symbols have exactly one pin of a POWER-type, which is _invisible_
>  4.13.iii power-flag symbols may have invisible value-fields (e.g. for Earth-symbols that are uniquely recognizeable by their symbol shape) (cf. KLC 4.9.ii)
>  4.13.iv the pin's name of power-flag symbols is the same as the symbol name

## PS: Some Images that may be used to illustrate the KLC:
![2017-06-05 12_02_40-part library editor d__kicad_kicad-library_library_graphic_symbols lib](https://cloud.githubusercontent.com/assets/11967523/26779767/fd3aa252-49e6-11e7-962f-8cdc16ac05cf.png)
![2017-06-05 12_02_15-part library editor d__kicad_test_addlin_ _kicad-library_library_power lib](https://cloud.githubusercontent.com/assets/11967523/26779769/fd3ee60a-49e6-11e7-8750-b3b3c2bab8c3.png)
![2017-06-05 12_01_48-part library editor d__kicad_test_addlin_ _kicad-library_library_power lib](https://cloud.githubusercontent.com/assets/11967523/26779768/fd3eefba-49e6-11e7-9aa8-d955654d7a0f.png)

Best,
JAN

**Comment by SchrodingersGat** [comment]
Thanks Jan these are good changes. I have adjusted KLC accordingly.

**Comment by poeschlr** [comment]
> Contain exactly one pin, which is invisible, and must be either Power Input or Power Output

Should we make it clear that only power input should be used for symbols that are intended to function as global labels? (I would even go so far to only allow invisible power input and make an exception for the power_flag. There is only one such symbol needed in the library.)

**Comment by SchrodingersGat** [comment]
@poeschlr you are right, I have now corrected this.

**Comment by jkriege2** [comment]
OK for me ... I adapted the scripts in my other PR to adapt to these rules.

JAN
