### ISSUE TITLE
Atmel library: SMD symbols lack pin for center pad

### ISSUE THREAD

**Issue by madworm** [KiCad/kicad-library#13]
At least one symbol (ATMEGA168A-M) [QFN32 + center pad (GND)] only has 32 electrical pins. The datasheet states that the center pad should be connected to GND, which requires another pin, e.g. #33.

The symbol should fully represent the device.

**Comment by keruseykaryu** [comment]
1. OK. Let the designer decide. When `atmel.lib` will be adjusted to KLC rules I will try to suggest to include bottom pad.
2. `QFNxx+EP` footprints has this pad numbered as n+1.
3. Like in 1. Let the designer decide, when we give him a choice.
