### ISSUE TITLE
Varistor ?

### ISSUE THREAD

**Issue by andres53016** [KiCad/kicad-library#131]
Hi I don't know where put de varistor symbol and the respective footprint.

**Comment by CarlPoirier** [comment]
Hi,

You already have a varistor in device.lib. It's called by its french name "varistance". That will need to be fixed. As for the footprint, it can be put in Discret.pretty. Thanks!

**Comment by andres53016** [comment]
Hi, here (https://github.com/andres53016/generator_siov) I write a python script to generate the footprints (144 footprints) from a table (siov_dimension.csv), the table I copy from www.epcos.com/inf/70/db/var_11/SIOV_Leaded_StandarD.pdf. I put this in Discret.pretty?
