### ISSUE TITLE
Modules cmake

### ISSUE THREAD

**Issue by hosier** [KiCad/kicad-library#132]
I'm probably doing something wrong
Output from running: "cmake CMakeLists.txt" in /kicad-library/modules

CMake Error at CMakeLists.txt:5 (install):
  install FILES given no DESTINATION!

CMake Error at CMakeLists.txt:9 (install):
  install FILES given no DESTINATION!

CMake Error at CMakeLists.txt:17 (install):
  install DIRECTORY given no DESTINATION!

CMake Error at CMakeLists.txt:22 (install):
  install DIRECTORY given no DESTINATION!

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.1)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!

**Comment by hosier** [comment]
Output errors from previous message are unrelated. I'm trying to add the modules and thought that I needed to run cmake somewhere.

**Comment by keruseykaryu** [comment]
Is it means that your issue report is invalid for kicad-library? If yes, please close it ASAP.
