### ISSUE TITLE
Minor KLC typo

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-library#1356]
@SchrodingersGat 
Section 4.9.i has bullets where I believe it should be lowercase letters. Can you please take a look?
![image](https://user-images.githubusercontent.com/1936989/27556105-239a35e2-5a69-11e7-81db-7ea2a8c4f311.png)

**Comment by SchrodingersGat** [comment]
Thanks @evanshultz I have fixed this.

Also, are you interested in helping out as a KiCAD librarian? Your continuing contributions have been greatly appreciated. I don't have your email address otherwise I would have PM'd you. Let me know here or by email if you're keen!

Thanks :)

**Comment by evanshultz** [comment]
@SchrodingersGat Yes. neaterbookmarks at gmail
