### ISSUE TITLE
missing USB3-MicroB connector.

### ISSUE THREAD

**Issue by davygrvy** [KiCad/kicad-library#1362]
The Micro-B has a different pinout with pin 4 being the OTG line.

**Comment by davygrvy** [comment]
[usb3_microb.zip](https://github.com/KiCad/kicad-library/files/1106643/usb3_microb.zip)

**Comment by evanshultz** [comment]
Hi @davygrvy!

I believe the libraries to have this covered. See the USB* symbols at https://github.com/KiCad/kicad-library/blob/master/library/conn.lib.

Unfortunately, symbol libraries aren't immediately updated (the footprint libraries are) and you need to wait for a new release of KiCad. Or you can individually update your symbol libraries.

Please take a look to see if the symbol you want is included in the latest library already.

**Comment by davygrvy** [comment]
![a](https://user-images.githubusercontent.com/2858064/27608227-7a039748-5b3b-11e7-8c5f-0717ddb030bb.jpg)

It's missing, sorry.  Thanks for the link

**Comment by evanshultz** [comment]
Alright. Since it seems you've already whipped up a symbol, please fork the library and submit your symbol with a pull request. Then the librarians can review the symbol and, once ready, add to the KiCad library. Thanks again for bringing this up and helping to improve KiCad!

**Comment by davygrvy** [comment]
My git chops are icky.  The connector graphic should be changed to represent the microB connector from the type B it currently is and I can't seem to get the library editor to do what I want for that.  Also, a 3.0 Micro AB is missing, too.  If someone could fix these, that'd be great.

**Comment by davygrvy** [comment]
Both of these are missing ![con-usb3-mini](https://user-images.githubusercontent.com/2858064/27707646-e415470e-5cca-11e7-907c-026d4e208033.png)

**Comment by poeschlr** [comment]
If symbols are missing, create them and if you want create a pull request to share them with other users. (Be the change you want to see.)

>  The connector graphic should be changed to represent the microB connector from the type B it currently is and I can't seem to get the library editor to do what I want for that.

What do you mean by that? maybe provide screenshots to show what you want to do. (And what part of it does not work.)

**Comment by suzizecat** [comment]
@davygrvy you will find out how to contribute with some explanations here : https://opensource.guide/how-to-contribute/

**Comment by poeschlr** [comment]
As this is about not yet contributed stuff and we already transferred the lib over to the v5 repo https://github.com/KiCad/kicad-symbols/, i will close this. If anybody involved in this discussion feels this needs to be reopened, feel free to reopen it on the v5 repo
