### ISSUE TITLE
Should "Display.3dshapes" be renamed to "Displays.3dshapes"?

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-library#1369]
Currently the 3d model lib for displays is named differently than its footprint lib.
I think this should be changed.
Any objections?

**Comment by Shackmeister** [comment]
+1

**Comment by SchrodingersGat** [comment]
+1

**Comment by SchrodingersGat** [comment]
See https://github.com/KiCad/kicad-library/pull/1376
