### ISSUE TITLE
Repository for PCB antennas

### ISSUE THREAD

**Issue by aliteke79** [KiCad/kicad-library#1378]
Hi guys, i have a PCB antenna footprint to share. Can you tell me the right repository name to contribute?

**Comment by SchrodingersGat** [comment]
Hi @aliteke79 we currently have the [RF Modules](https://github.com/KiCad/RF_Modules.pretty) repository which is for RF front-end modules. However this is probably not appropriate for antennae.

Do you have a link to the particular datasheet for the antenna? This might influence our decision.

Perhaps a new repository named `RF_Antenna.pretty` would be acceptable? @jkriege2 @poeschlr any thoughts on this?

**Comment by jkriege2** [comment]
I would vote for such a repo ...
JAN

**Comment by pointhi** [comment]
I would also vote for such a repo.

Any thoughts about printed pcb-antennas, which would only consist of some copper? Would supporting such footprints in the library make sense? (they are to some extend dependent on pcb properties)

**Comment by aliteke79** [comment]
yes, http://www.ti.com/lit/an/swra117d/swra117d.pdf

**Comment by aliteke79** [comment]
![small_size_2 4g_pcb_antenna-copper](https://user-images.githubusercontent.com/8535913/27784455-bdac4ed0-5fe2-11e7-83d3-66accbc72b54.png)

**Comment by suzizecat** [comment]
@pointhi Since it could be quite painful to make, i'll vote to support them as a standard footprint.
BTW i already have an antenna into RF_Modules but i vote for an antennae specific repo

**Comment by SchrodingersGat** [comment]
Such items can be considered footprints, I'd support adding them.

**Comment by SchrodingersGat** [comment]
https://github.com/KiCad/RF_Antenna.pretty

**Comment by SchrodingersGat** [comment]
PR for lib-table entries here - https://github.com/KiCad/kicad-library/pull/1379

**Comment by hackscribble** [comment]
Most (all?) of the other footprint repos have plural names (e.g. `Housings_xxx`, `Connectors_xxx`).  Maybe this new one should be `RF_Antennas` for consistency?

**Comment by aliteke79** [comment]
Thank you all, i'm going to fork and add it

**Comment by SchrodingersGat** [comment]
Thanks for raising the issue @aliteke79
