### ISSUE TITLE
Cirrus CS8420: Multifunction pins on symbols

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-library#1423]
I was ready to add [CS8420 ](https://d3uzseaevmutz1.cloudfront.net/pubs/proDatasheet/CS8420_F4.pdf)to the library, but I found a symbol already existed named `CS8420_SOFT`:
![image](https://user-images.githubusercontent.com/1936989/28365689-5aeba8be-6c3e-11e7-9e92-9014b8d35073.png)

This symbol only covers the pin configuration of CS8420 when in software mode (where digital communication is provided for an external processor to configure the IC).

This is shown in the datasheet on page 51:
![image](https://user-images.githubusercontent.com/1936989/28365749-9ab1c97e-6c3e-11e7-86dd-957467c15ebb.png)

In addition, there are not one but 6 (yes, really, six) hardware modes. Page 57:
![image](https://user-images.githubusercontent.com/1936989/28365769-b32c58a2-6c3e-11e7-8b99-4e69709ba6c1.png)

Page 61:
![image](https://user-images.githubusercontent.com/1936989/28365787-c4de1072-6c3e-11e7-86b1-c53d36ec0e57.png)

Page 65:
![image](https://user-images.githubusercontent.com/1936989/28365802-d41a8246-6c3e-11e7-877a-90018dc75e54.png)

Page 69:
![image](https://user-images.githubusercontent.com/1936989/28365818-e0dbd2b4-6c3e-11e7-9b84-94f4633f9392.png)

Page 72:
![image](https://user-images.githubusercontent.com/1936989/28365829-ed12e7e8-6c3e-11e7-95c8-cfab37f50c25.png)

And finally, page 76:
![image](https://user-images.githubusercontent.com/1936989/28365839-fc113f2e-6c3e-11e7-904a-0ac3676f4f06.png)

Is there already a known good method to handle this situation? CS8420 is obviously a special case with 7 different pin configurations, so maybe it's just an outlier and we haven't come across this before?

On microcontrollers I've seen we use the "base" pin number, like `PA1` instead of `PA1_UART5_RTC_ADC0` or some other long pin name. That wouldn't seem to apply here since there isn't a singular name for each pin (only 3 pins are common in all modes) that can be referenced in the datasheet.

Having separate symbols seems a bit lame but maybe that's the best option? If we were to combine the pin names for all the hardware modes into one symbol, we'd end up with these pins names:
```
1: COPY/C
2: DFC0
3: ~EMPH/U/V
4: RXP/SMFT0
5: RXN/SFMT1
6: VA+
7: AGND
8: FILT
9: ~RST
10: RMCK/APMS
11: RERR/~LOCK/TBCLD
12: TCBLD/ILRCK/RCBL
13: PRO/C/ISCLK
14: MUTE/SDIN/CHS
15: TCBL/NVERR
16: OSCLK/CEN
17: OLRCLK/V
18: SDOUT/U
19: ~AUDIO/V/CUVEN
20: S/~AES/PRO/C
21: OMCK/APMS
22: DGND
23: VD+
24: H/S
25: TXN/U
26: TXP/C
27: DFC1
28: ORIG/U
```

That seems rather ugly to me. But so does having 7 symbols for this part. Any suggestions?

**Comment by suzizecat** [comment]
You can have a look at any STM32 MCU (which are script-generated) to see that it's handled with pins combined. Since any combinaison is possible, this is a little bit different but you get the thing.

IMHO it would be fine that way.

**Comment by SchrodingersGat** [comment]
The STM32 libs are the logical extension of this approach, and (IMO) they are ridiculous. Some take up almost an entire sheet of (A4) paper.

But as you state @evanshultz these are the two options - one symbol with large names or multiple symbols.

For this I would go with large names:

a) Less to rework later
b) When we (eventually) convert to the new library format we can enumerate each pin function

**Comment by evanshultz** [comment]
Another option would be to only give pin numbers, not names, but that's unlike any other IC I've seen and just seems bad practice. I only mention it since even a bad solution is still a solution.

@SchrodingersGat So you're OK if I rework the existing symbol to make it work for all modes?

**Comment by SchrodingersGat** [comment]
@evanshultz I think so - the names are not "too" long, for this one.

**Comment by suzizecat** [comment]
@SchrodingersGat Got to say that STM32 symbols are absolutely insanes (need A2 paper for STM32L4...) ^^'

**Comment by SchrodingersGat** [comment]
@suzizecat yes I have it on my list to fix but my list is very very long.. If anyone else gets around to doing this... ;)
