### ISSUE TITLE
Footprint TO_SOT_Packages_SMD:SOT-23 and 3D model pins does not match

### ISSUE THREAD

**Issue by vpelaez** [KiCad/kicad-library#1435]
I have just installed version 4.0.6 64 bits in Windows 10 and found that pins in the 3D model of the TO_SOT_Packages_SMD:SOT-23 footprint does not match the footprint representation. Please see the following image.
![sot23](https://user-images.githubusercontent.com/24358407/28494406-dbe49c04-6f2d-11e7-8238-8087b4fddef5.PNG)

I think that the 3D figure needs to be rotated clockwise to match the pads.

When using this footprint in a PCB the 3D viewer shows the same problem.

This problem is not present in the TO_SOT_Packages_SMD:SOT-23-5 footprint.

**Comment by Shackmeister** [comment]
Hello I can see from the screenshot you are using the old 3D model, you should update them to the newest :) see more here: https://forum.kicad.info/t/incorrect-component-models-in-3d-viewer/7011/5

**Comment by Shackmeister** [comment]
Also make sure you have the latest footprints while you are at it :)

**Comment by Shackmeister** [comment]
@vpelaez did you have ny luck solving it?

**Comment by vpelaez** [comment]
Hello @Shackmeister, you are very right, I have just downloaded the new 3D models and it is working as expected now. Thank you very much for your help.
