### ISSUE TITLE
How should keepout areas be shown in footprints

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-library#1443]
Keepout zones can not be defined in footprints. How should we show that a footprint has an area where no copper should be placed.

I have seen the following options:
 1. dwgs.user layer for the zone outline plus text on cmts,user (Example: https://github.com/KiCad/RF_Modules.pretty/pull/16)
 1. everything on the fab layer. (Example: https://github.com/KiCad/Connectors_Hirose.pretty/pull/17)

We should fix it in the klc such that all footprints follow the same rule and the user of our libraries knows what to expect.

I vote for option 1. (Fab layer is for the documentation. If we put stuff like keepout areas on this layer, it gets very crowded.)

**Comment by hackscribble** [comment]
+1 for option 1 

Would we also want to specify the visual style of the keepout?  For example, one of the following ...

![image](https://user-images.githubusercontent.com/7076027/28592177-0fc1b4f4-7180-11e7-83ba-be9cb6ce1749.png)

**Comment by evanshultz** [comment]
I like option 1a: hatched lines on Dwgs.User.

**Comment by poeschlr** [comment]
I would say a or b plus maybe a text on comments that specifies what the drawing means.
Some footprints say no copper, others might specify no vias (no bare copper), others might specify no tracks except ground, ...
Or should we define different styles for different meanings?

**Comment by hackscribble** [comment]
My preference would be for just one style with the meaning explained in comments.

This example is hatched on Dwgs.User and text on Cmts.User ...

![image](https://user-images.githubusercontent.com/7076027/28617747-9cc4e6d6-71f9-11e7-8368-009911fdc198.png)

**Comment by SchrodingersGat** [comment]
Option a) works best IMO, especially for irregular regions. Is there any reason that the explanatory text (on User.Comments) should not be overlaid on the same space? It makes it a bit harder to read but it's obvious in high-contrast layer mode

**Comment by hackscribble** [comment]
This is with high-contrast button enabled (4.0.7 on Ubuntu in OpenGL). 

![image](https://user-images.githubusercontent.com/7076027/28618768-76a37c84-71fd-11e7-90fe-3ae1fb026c40.png)

**Comment by SchrodingersGat** [comment]
Are they both on the same layer? Here's what I get, OpenGL on Ubuntu:

![screenshot from 2017-07-26 21-29-57](https://user-images.githubusercontent.com/10080325/28618963-b92dafb0-7249-11e7-9010-adaf1996976d.png)

![screenshot from 2017-07-26 21-30-07](https://user-images.githubusercontent.com/10080325/28618964-bbdba334-7249-11e7-8fed-bc9ff1a62f8f.png)

**Comment by hackscribble** [comment]
Mine are definitely on Dwgs and Cmts.  Here is the view in OpenGL without the contrast button enabled.

![image](https://user-images.githubusercontent.com/7076027/28619108-c91082cc-71fe-11e7-84b4-cef3cb0c6819.png)

**Comment by hackscribble** [comment]
Also, can I check that it is not possible in footprint editor to write directly to either of these layers?  One needs to write onto another layer and then edit the properties (or edit the file) to move the lines and text to the .User layers?

**Comment by poeschlr** [comment]
@hackscribble set the active layer different to either commends or drawings while in highcontrast.
@SchrodingersGat set the active layer equal to drawings in the first screenshot and equal to comments in the second.
That's why they look different.

**Comment by poeschlr** [comment]
@hackscribble Yes one can not directly draw on these layers. (But this might be something we can request from the developers. Maybe we can even get a dedicated layer in v5?)

**Comment by SchrodingersGat** [comment]
@poeschlr I would like to have a working keepout, rather than a layer dedicated to keepout. 

This would require that keepouts can be assigned multiple layers, I think. I have a code branch where this is possible (spawned from this discussion) but it requires more work.. Hopefully I get time to work on this pre v5

**Comment by suzizecat** [comment]
I would also point out that IMHO it'normal that FP designer can't write on these layers since it's "User" Comment and "User" drawings... There should be something dedicated

**Comment by poeschlr** [comment]
If keepout zones can be used in the footprint that would be even better. But if this does not get finished in time, it might be a good idea to include a special graphical layer for keepouts on top and bottom. (Yes dirty workaround but better than nothing.)

**Comment by suzizecat** [comment]
> it might be a good idea to include a special graphical layer for keepouts on top and bottom. (Yes dirty workaround but better than nothing.)
Well, in this case, you should add one keepout layer by copper layer...
In example, in RF design you often have to clear copper on all layers (or all layers except the last one)

**Comment by poeschlr** [comment]
Lets hope oliver finishes the implementation of keepout support for footprints.

**Comment by hackscribble** [comment]
> Lets hope oliver finishes the implementation of keepout support for footprints.

In the meantime, is there still value in adding something to KLC to specify a purely graphical and text note representation?  If we (improperly) use the .User layers, at least it would be easy to trawl all footprints later to identify those that need upgrading to the new implementation.

Or are there relatively few contributions with keep-out zones, so this is not a big issue?

**Comment by poeschlr** [comment]
I would at least fix the style we want to use until v5 comes out.

If i read all your posts correctly i think we all agree with version 1a (cross hatched area on drawings layer plus text on comments layer.)

**Comment by SchrodingersGat** [comment]
I will update the KLC with such a rule - I'm away until Tuesday so not until then.

**Comment by SchrodingersGat** [comment]
I have added this to the KLC, new rule 7.8

**Comment by poeschlr** [comment]
Thanks. I assume i can close this now. (If anyone disagrees simply reopen it.)
