### ISSUE TITLE
BOM export to CSV fails

### ISSUE THREAD

**Issue by chrisspen** [KiCad/kicad-library#1521]
If I select /usr/lib/kicad/plugins/bom2csv.xsl as a BOM plugin and click Generate, I get the error:

    Run command:
    xsltproc -o "/usr/local/myproject" "/usr/lib/kicad/plugins/bom2csv.xsl" "/usr/local/myproject/circuit1.xml"

    Command error. Return code -1

    Error messages:
    execvp(xsltproc, -o, /usr/local/myproject, /usr/lib/kicad/plugins/bom2csv.xsl, /usr/local/myproject/circuit1.xml) failed with error 2!

Although this error doesn't really tell you what's wrong, manually running the command told me that `xsltproc` was not installed, and running `sudo apt install xsltproc` quickly fixed the problem.

It might be helpful if xsltproc were listed as a package dependency, so it's automatically installed along with KiCad.

**Comment by poeschlr** [comment]
This is the wrong place to report this issue.

Problems with kicad it self need to be reported over at the [bugtracker](https://bugs.launchpad.net/kicad/)

This repo is only for the symbol and 3d model libraries. (And maybe for general topics about the footprint lib as well.)
