### ISSUE TITLE
How to resolve mess and hotchpotch in `special.lib`

### ISSUE THREAD

**Issue by keruseykaryu** [KiCad/kicad-library#153]
I think `special.lib` is a type of bag in which very strange things were thrown. Here are my proposals how to clean up this mess and finally remove this problematic baggage.

However, I still have a lot of doubts where to put some devices indicated by '???'.

| Device | Move to | Info
|---|---|---
| 20RS10 | Lattice.lib | New library
| 74LS629 | 74xx.lib | 
| 754C923 | 74xx.lib or Interface.lib **???** | Correct name is: MM74C923
| 75LBC176 | Interface.lib | 
| 9346 | Memory.lib | 
| AD725 | Video.lib | 
| _ADUC816_ | **REMOVE** | Already exist
| AV9173 | Video.lib | 
| CX7930 | Video.lib | 
| DG884 | Analog_Switches.lib | 
| DP83848I | Interface.lib | 
| DS1267 | Maxim.lib | 
| DS1302 | Maxim.lib | 
| DS1307+ | Maxim.lib | 
| DS1307N+  | Maxim.lib | 
| DS1307Z+ | Maxim.lib | 
| DS1602 | Maxim.lib | 
| DS1621 | Maxim.lib | 
| DS1804 | Maxim.lib | 
| DS7820 | Interface.lib | 
| DS7830 | Interface.lib | 
| DS8830 | Interface.lib | 
| DS90C124 | Interface.lib | 
| DS90C241 | Interface.lib | 
| EL2001 | Interface.lib | 
| EL7242C | Interface.lib | 
| EP1210 | Altera.lib | New library
| EP1810 | Altera.lib | New library
| EP300 | Altera.lib | New library
| EP310 | Altera.lib | New library
| EP320 | Altera.lib | New library
| EP600 | Altera.lib | New library
| EP910 | Altera.lib | New library
| FD1771 | Interface.lib | 
| FD2791 | Interface.lib | 
| FD2795 | Interface.lib | 
| HA2540 | Linear.lib | 
| HA5033 | Linear.lib | 
| HCLD0438 | Display.lib | 
| HCPL2731 | Opto.lib | 
| HD63484 | Video.lib | 
| HD63484_PLCC | Video.lib | 
| HI524 | Analog_Switches.lib | 
| HM53461 | Memory.lib | 
| HM53462 | Memory.lib | 
| ICL7660 | DC-DC.lib | 
| ICM7209 | Interface.lib | 
| IDT7132 | Memory.lib | 
| IDT7201 | Memory.lib | 
| IDT7202 | Memory.lib | 
| IQXO/7X | Oscillators.lib | New library
| IRF7404 | Transistors.lib | 
| LCD4 | Display.lib | 
| LIGNE_A_RETARD | Device.lib | 
| LM16255K | Display.lib | 
| LM1881 | Video.lib | 
| LM35 | Sensors.lib | 
| LM5051 | Power_Management.lib | New library
| LT1080 | Interface.lib | 
| LTC1257 | ADC-DAC,lib | 
| LTC4007 | Power_Management.lib | New library
| M3003 | Interface.lib **???** | Realtime Clock
| MAX232 | Interface.lib | 
| MAX202 | Interface.lib | 
| MAX2606 | Maxim.lib | 
| MAX2505  | Maxim.lib | 
| MAX2507 | Maxim.lib | 
| MAX2508 | Maxim.lib | 
| MAX2509 | Maxim.lib | 
| MAX310 | Video.lib | 
| MAX311 | Video.lib | 
| MAX3226 | Interface.lib | 
| MAX453 | Maxim.lib | 
| MAX5436 | Maxim.lib | 
| MAX6355 | Maxim.lib | 
| MAX666 | Regul.lib  | 
| MAX777 | DC-DC.lib  | 
| MB81461ZIP | Memory.lib | 
| MB88303P | Video.lib | 
| MC1413 | Interface.lib | 
| ULN2003  | Interface.lib | 
| ULN2003A | Interface.lib | 
| MC1413P | Interface.lib | 
| MC1417 | Interface.lib | 
| MC33064D | Power_Management.lib | New library
| MC34064D | Power_Management.lib | New library
| MC34064P | Power_Management.lib | New library
| MC33064P | Power_Management.lib | New library
| MC3486 | Interface.lib | 
| MC3487 | Interface.lib | 
| MK4501 | Memory.lib | 
| MK4511 | Memory.lib | 
| MT43C4257 | Interface.lib | 
| MT43C4258 | Interface.lib | 
| Max691 | Maxim.lib | 
| PAL16L8 | Lattice.lib | New library
| PAL20L8 | Lattice.lib | New library
| PCI9030-PQFP176 | Conn.lib | 
| **RT9701** | Power_Management.lib | New library. Symbol waiting in merge request.
| S5933_PQ160 | Interface.lib | 
| SA605D | RF_Devices.lib **???** | FM Radio Mixer
| SI582 | Video.lib | Video ampllifier
| SI9986 | Interface.lib | 
| SRV05 | ESD_Protection.lib | New library
| S_178 | Video.lib | After rename to S178
| Si570 | Oscillators.lib | New library
| Si571 | Oscillators.lib | New library
| TC524256Z | Memory.lib | 
| TCXO3 | Oscillators.lib | New library
| TCXO_DFAS11 | Oscillators.lib | New library
| TDA1950 | Video.lib | 
| TDA1950F | Video.lib | 
| TDA7260 | Video.lib | 
| TDA_2593 | Video.lib | After rename to TDA2593
| TDA_9500 | Video.lib | After rename to TDA9500
| TDA_9503 | Video.lib | After rename to TDA9503
| TDA_9513 | Video.lib | After rename to TDA9513
| TDC1408 | ADC-DAC.lib | 
| TEA2014 | Interface.lib | 
| TEA5115 | Video.lib | 
| TIL111 | Opto.lib | 
| _TL431_SOT-23-3_ | **REMOVE** | Already exist
| _TL431_TO92_ | **REMOVE** | Already exist
| TL7702 | Power_Management.lib | New library
| TL7705 | Power_Management.lib | New library
| TMS320LF2406 | Texas.lib | 
| TMS4C1050N | Memory.lib | 
| TPD2S017 | ESD_Protection.lib | New library
| TPD4S1394 | ESD_Protection.lib | New library
| TQSMT-35 | Oscillators.lib | New library
| U2270B | Interface.lib | 
| UA9637 | Interface.lib | 
| UA9638 | Interface.lib | 
| UVC3100 | ADC-DAC.lib | 
| UVC3101 | ADC-DAC.lib | 
| X9118 | Xicor.lib | New library
| X9250 | Xicor.lib | New library
| X9258 | Xicor.lib | New library
| X9258-PART | Xicor.lib | New library
| Z8530 | Zilog.lib | New library

Do you have any other proposals or have different solutions than showed above?

**Comment by ricardocrudo** [comment]
What about PMIC (power management integrated circuit) for: MC33064D,MC34064D,MC34064P,MC33064P,TL7702,TL7705

**Comment by keruseykaryu** [comment]
> What about create pmic.lib (power management integrated circuit) for: MC33064D,MC34064D,MC34064P,MC33064P,TL7702,TL7705

I have suggested new `power_management.lib` library to which these parts can be moved to. IMO, we have to avoid shortcuts - as possible - in library names.

**Comment by ricardocrudo** [comment]
more suggestions:
SA605D: rfcom
SRV05, TPD2S017, TPD4S1394: esd_protection.lib or transient_voltage_suppression.lib (TVS)
Si570, Si571: oscillators.lib or programmable_oscillators.lib to be more specific.
Actually, maybe, clock_generators.lib could be oscillators.lib.

**Comment by keruseykaryu** [comment]
`esd_protection.lib` sounds reasonable. `oscillators.lib' - Short and pithy.

**Comment by keruseykaryu** [comment]
> more suggestions:
> SA605D: rfcom

This is an FM radio component. IMO this is not a strict RF data communication device.

**Comment by nickoe** [comment]
So maybe rf_mixers for the SA605D?

**Comment by keruseykaryu** [comment]
I'm looking for some more universal name for radio devices, also for the future symbols that might appear.

**Comment by nickoe** [comment]
So what about radio_devices or rf_devices?

**Comment by CarlPoirier** [comment]
Hi Kerusey,

Thanks for taking care of this.

Here is some more information on unknown parts:

S178 is a video pulse generator http://pdf.datasheetarchive.com/indexerfiles/Scans-052/DSAIH00054578.pdf
SI582 might be a video amplifier but I'm not sure at all.
M3003 is actually M3002 http://www.mixinc.net/atari/datasheet/M3002.pdf

**Comment by ChlorideCull** [comment]
I find some battery chargers in `regul.lib`, which isn't really the place for them (they don't strictly do only regulating). Splitting them out to a `power_management.lib` would be a really nice solution.

**Comment by keruseykaryu** [comment]
> I find some battery chargers in regul.lib, which isn't really the place for them

Would you tell us which they are?
Your #168 also is a candidate to put it in the different library.

**Comment by keruseykaryu** [comment]
> @CarlPoirier: SI582 might be a video amplifier but I'm not sure at all.

I have found one DS (http://www.farnell.com/datasheets/1748226.pdf) where Si582 is referenced as video amplifier.

The destination list is now almost complete. Please review once more.

**Comment by ChlorideCull** [comment]
>Your #168 also is a candidate to put it in the different library.

Yeah, I placed it for there since the others are there, and as of right now there isn't a better place to put them. They can be moved when there is. The parts in `regul` as of right now are:

* MAX1647 (Battery Charger)
* MAX1648 (Battery Charger)
* BQ2003 (Controleur de chargeur de batteries)

**Comment by CarlPoirier** [comment]
@keruseykaryu It looks great on my end. Can we get this merged before we proceed to rename the libraries with capital letters? I talked about April 8th in the other discussion #161 , but I think we should prioritize this. Are there any merges that must go through before this one?

**Comment by ChlorideCull** [comment]
I've taken the liberty to move over the battery charger and #168 into `Power_Management.lib`. Pull request #171.

**Comment by keruseykaryu** [comment]
> Can we get this merged before we proceed to rename the libraries with capital letters?

Sorry Carl, but I can not find some spare time to split this library.

> Are there any merges that must go through before this one?

#152 #145

**Comment by CarlPoirier** [comment]
I myself don't have much time either. I suggest we undertake this bits by bits and write in the Info column whenever some parts are done.

**Comment by ricardocrudo** [comment]
I did a script that can be helpful in this work of moving parts. It's in my repo https://github.com/ricardocrudo/kicad-utils and is called move_part.py, inside of schlib directory. The output library file will probably have other modified parts, besides of the "move" content. Because the script uses other algorithm to generate library files.

**Comment by CarlPoirier** [comment]
This should be it in #181. Can anyone go over the changes?

**Comment by ricardocrudo** [comment]
Hmm, ok. I'll check this flag. Thanks by report.

I've checked Carl's request, each part. Everything is OK, ready to merge.

**Comment by CarlPoirier** [comment]
Thanks Ricardo.
