### ISSUE TITLE
Error message in analog devices lib: AD637xQ not found

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad-library#1567]
@evanshultz:
There is either a symbol or alias missing in the analog devices lib.
Could you add the one that is missing? (I would do it but i don't know what you had planned for this dcm entry to represent.)
![screenshot from 2017-08-24 00-01-53](https://user-images.githubusercontent.com/18327350/29640741-93906d06-8860-11e7-9e41-7e0be795620e.png)

**Comment by evanshultz** [comment]
This should have been fixed with https://github.com/KiCad/kicad-library/pull/1558, but I inadvertently removed AD637xQ at the same time as fixing the other things. PR at https://github.com/KiCad/kicad-library/pull/1568.
