### ISSUE TITLE
Move / link .pretty repos into kicad-library

### ISSUE THREAD

**Issue by gauravjuvekar** [KiCad/kicad-library#1575]
It's a bit cumbersome to keep all the .pretty repos synced individually. Can we create a new `footprints` folder in this repo and put all of the `.pretty` repos inside that using `git submodule`?

Pros
- Nothing much changes for existing users --- they will have to explicitly do `git submodule update --init --recursive`
- People who want to use the 'bleeding edge' git repos can do so more easily with a simple repo.

Cons
- Lib maintainers will have to frequently update the submodule commits (though someone could use a script for this).

**Comment by poeschlr** [comment]
There is a script that does all the work for you:
https://github.com/KiCad/kicad-library-utils/blob/master/download_pretty_libs.py

**Comment by poeschlr** [comment]
@gauravjuvekar to clarify. I don't agree with moving repo libs into the symbol repo. In future I the setup will be 3 main repos: symbol-library, footprint-library, packages3d
With support repos for templates, packages3d-source, ...

But this is some time in the future. It does not look like we can get it for v5. (the github plugin needs the current setup. There is no sign this will change in v5.)

**Comment by gauravjuvekar** [comment]
Closing since this is addressed a lot elsewhere on dev mailing list and on forums.
