### ISSUE TITLE
TO_SOT_Packages_SMD:SOT-223-3Lead_TabPin2 - 3D model size and rotation

### ISSUE THREAD

**Issue by MartinStej** [KiCad/kicad-library#1625]
It seems that this model is about 2x times bigger and rotated by 90 deg.
![01](https://user-images.githubusercontent.com/25244616/30514272-db855e0a-9b11-11e7-8899-e29d330d0506.png)
![02](https://user-images.githubusercontent.com/25244616/30514273-deeed9c2-9b11-11e7-9492-b75d881ca092.png)

**Comment by Shackmeister** [comment]
Try updating your 3D models, this can be done from within PCBnew or through git

**Comment by MartinStej** [comment]
Thanks for answer. After update everything is just fine. Sorry for false alarm.
