### ISSUE TITLE
INA138/INA168 Schematic symbol has incorrect pinout

### ISSUE THREAD

**Issue by danwood76** [KiCad/kicad-library#1631]
In the latest linear.lib (included in KiCAD version 4.0.7) the pinout for the newly added INA138 and INA168 are incorrect.

The pinout of the library version is:
1: Out
2: GND
3: V+
4: -IN
5: +IN

Whereas in the TI datasheet (can be found from the schematic symbol) it is listed as:
1: Out
2: GND
3: +IN
4: -IN
5: V+

**Comment by SchrodingersGat** [comment]
@danwood76 it appears you are correct! Do you want to issue a PR (pull request) to fix this?

**Comment by danwood76** [comment]
@SchrodingersGat I think I have managed to make the changes and do the pull request: #1632

**Comment by SchrodingersGat** [comment]
Awesome! Thanks for fixing this
