### ISSUE TITLE
DIN 5-pin connector with non standard numeration

### ISSUE THREAD

**Issue by ricardocrudo** [KiCad/kicad-library#164]
Looking at the DIN_5 symbol from conn.lib I've checked that the pins numbers are numerated sequentially but the standard DIN 5-pins connectors used to have another numeration way, like the following references:
http://www.mouser.com/ds/2/670/sds-xxj-535158.pdf
http://www.mouser.com/ds/2/209/KC-301191-193300.pdf

Is this a bug or desired feature? I'm needing a standard 5-pin din connector, thus I'd like to know if I fix this one or keep it and create another one.

**Comment by samdolt** [comment]
I didn't found any corresponding footprint in the library. Did you find one?

**Comment by keruseykaryu** [comment]
![din5](https://cloud.githubusercontent.com/assets/6367557/6901615/cf9704d2-d70e-11e4-9c52-48ddbc40e901.png)

**Comment by keruseykaryu** [comment]
This symbol doesn't have any corresponding footprint. To be in accordance with the standard pinning, we need to improve that symbol. Even if this connector type is a bit obsolete.

**Comment by CarlPoirier** [comment]
Can you find a DIN_5 with that pinout? If not, then you can fix this one.

**Comment by keruseykaryu** [comment]
I'm pretty sure we do not find this pin arrangement. 
IMO this is one of the results of joyful productivity from some user who never saw German DIN 41524.

**Comment by CarlPoirier** [comment]
Fixed in latest pull request from Ricardo. Thanks!
