### ISSUE TITLE
Parse error with net class

### ISSUE THREAD

**Issue by Ruffunaru** [KiCad/kicad-library#1665]
Hello,

I want to see the Kicad project of the DIY Laptop by Olimex.
When I open the .kicad_pcb file with Pcbnew, I got an error :

"Error loading board.
KiCad was unable to open this file, as it was created with a more recent version than the one you are running. To open it, you'll need to upgrade KiCad to a more recent version.

Date of KiCad version required (or newer): 08/15/16

Full error text:
PARSE_ERROR: Expecting 'clearance, trace_width, via_dia, via_drill, uvia_dia, uvia_drill, or add_net' in input/source
'/home/Ruffunaru/KiCad_Project/DIY_Laptop_olimex/HARDWARE/A64-TERES/TERES-PCB1-A64-MAIN/TERES_PCB1-A64-MAIN_Rev.B.kicad_pcb'
line 580
offset 6
from dsnlexer.cpp : Expecting() : line 369"

My version of Kicad : 4.0.7-e2-6376~58~ubuntu16.04.1, release build

When I open the .kicad_pcb file with my text editor (gedit)
I find the keywords above (clearance, via_dia, add_net, etc) but there is also two others keywords : "diff_pair_gap" and "diff_pair_width"

I presume that there are net class from an older version and there are not here anymore. Am I right ?

I think that I have to open this file with an older version but I wanted to ask here if there is an easier solution.

Thanks in advance :)

**Comment by poeschlr** [comment]
This is the wrong place to report such an issue.
I would suggest the [kicad forum](https://forum.kicad.info/) in this case.

It seems the project has been created with some newer version of kicad. Probably a nightly build version.
