### ISSUE TITLE
Maple Mini library symbol is for an obsolete device

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [KiCad/kicad-library#1668]
The library symbol for the Maple Mini (STM32 CPU board module) is for an obsolete device which can no longer be purchased as it was discontinued several years ago

https://www.sparkfun.com/products/retired/11280

Clones of this board are still widely available, e.g on eBay, AliExpress or Amazon etc, however their pinout is slighly different from the symbol add to the library

Specifically the AV- and AV+ pins are incorrect

https://github.com/KiCad/kicad-library/blob/master/library/modules.lib#L248
https://github.com/KiCad/kicad-library/blob/master/library/modules.lib#L275

The schematic for the clones appears to be this

http://wiki.stm32duino.com/images/2/26/Maple_mini_clone_schematic.JPG

Hence pin AV+ is now Vcc and AV- is now GND

I recommend, either the symbol name is changed to make it clear that this is for an obsolete product, or that name is changed to Maple mini (clone) and those pins changed to reflect the hardware which people can buy

**Comment by bobc** [comment]
I propose to fix this by creating a new component "Maple_Mini_Clone". I am reluctant to change existing components and break back compatibility.
I have created a component, I just need to run KLC cleanup before submitting PR.

**Comment by rogerclarkmelbourne** [comment]
@bobc 

Sounds good to me.

**Comment by Rantanen** [comment]
Good points. When I originally PR'd the Maple Mini, I knew about it having been discontinued, but thanks to the clones being available I justified the symbol anyway.

This of course resulted in the question of which pinout to implement in the symbol. My justification for the AV+/AV- pins were:

- They are documented. The current clones happen to have VCC/GND in their place, but that's not guaranteed to be the case with all the clones.
- Labeling them AV+/AV- isn't completely wrong for the clones, you can still use them as reference voltages for the analog circuitry - just a rather crappy one. The opposite of labeling them as VCC/GND and using them with the original Maple Mini would have been worse as this might have lead people to use them as "general purpose power output" when powering through USB for example.

That latter point is even worse, if labeling them VCC/GND makes KiCad insist on connecting them with the other VCC/GND pins on the PCB. As per the or iginal design, the board should be able to be powered through one pin.

In any case, if a new component is made, I'd propose it to be named "Maple_Mini_Baite", as that's [the board](https://www.robotshop.com/letsmakerobots/files/maplemini2.jpg) the proposed pinout is based on. As far as I know, that's the only clone there is for now, but there is always the possibility that might change.

Although now I'm curious. Can we add a second footprint that duplicates the VCC/GND pins and omits the AV+/AV-? Or would this need a new VCC/GND pair in the symbol?

Technically I guess this conversation belongs in the new repo, but I didn't feel like starting a new issue there.

**Comment by rogerclarkmelbourne** [comment]
@Rantanen 

No worries

I just thought I should let everyone know that this symbol is not correct for the clones.

I'm also not sure if all the clones are made by Baite, and even Baite now seems to have rebranded to another name (though I can't remember off the top of my head what they call themselves now)

So perhaps any new symbol should just possibly be named Maple Mini clone

**Comment by poeschlr** [comment]
@rogerclarkmelbourne this repo will be archived shortly. If this particular problem still persists could you reopen this over at the new repo https://github.com/KiCad/kicad-symbols? (Add a short summary and point back to this issue)
