### ISSUE TITLE
VSOURCE symbol of pspice.lib is too huge

### ISSUE THREAD

**Issue by efferre79** [KiCad/kicad-library#1684]
I have just installed kicad and kicad-libraries from the github repositories compiling from source. As a tutorial I am trying to draw a schematic and simulate it with ngspice. I have loaded the pspice.lib (/usr/share/kicad/library/pspice.lib) but the symbol for the VSOURCE is definitely too huge comparing to the other symbols, here is a snapshot:

![snap](https://user-images.githubusercontent.com/4586973/31166195-32d752d2-a8ee-11e7-91ca-b864ef9739ab.png)

Looking at the video tutorial https://www.youtube.com/watch?v=2WDPzW6DGzQ, it looks regular. Is it a problem of the library or kicad?

**Comment by SchrodingersGat** [comment]
It does look like it needs to go on a diet. Are you able / willing to submit a pull request to address this?

**Comment by efferre79** [comment]
I have just started using kicad so I don't have confidence at all with the software and the libraries, I don't think I am able right now to fix the issue by myself :-( But I am available to test the changes in the library.

**Comment by SchrodingersGat** [comment]
I have submitted a change (see above).

**Comment by SchrodingersGat** [comment]
This has been fixed now, thanks for bringing it to our attention.

**Comment by efferre79** [comment]
I have tested the changes, now it looks better but I think it can be made smaller. I am attaching another attachment below where I put the voltmeter symbol (from device.lib) as a reference, in my opinion the circle of VSOURCE can be made as small as the one for the voltmeter.

![snap1](https://user-images.githubusercontent.com/4586973/31234441-30690aac-a9ef-11e7-98f4-e9eb0378f589.png)

What do you think?
