### ISSUE TITLE
Kingbright Display library

### ISSUE THREAD

**Issue by brekee12** [KiCad/kicad-library#1722]
Hi there,

Kingbright make available it's LED display 3D CAD files. I could convert IGES files to DXF but I could not create a part from it. Could you help me how to do it or help to do it.
Thanks in advance!

**Comment by SchrodingersGat** [comment]
Not quite sure what you are asking. Do you want to convert the DXF files to a footprint, or use the data to manually create footprints yourself?

**Comment by brekee12** [comment]
I would like to use Kinbright ACSC08-51QBWA/D LED display. It is a new SMD
package which has a CAD drawing (IGES) publicly available. I was succesful
to convert it to DXF by FreeCAD and I could import it, but unsuccessful to
make a 3D parts from that. I would like to do it by myself to learn it, if
it is possible; but I have seen 3D packages are on GitHub and they are in
special .pretty fileformat, which are managed by KiCAD team. What would be
the correct methode: request to make this library component by the team or
please suggest material how to do it myself.

2017-10-15 9:09 GMT+02:00 Oliver <notifications@github.com>:

**Comment by bobc** [comment]
Ok, there is a lot of confusion here. The .pretty file contains the _footprint_ only, but it can also include the file name of a 3D model if there is one.

The 3D model is a completely separate file to the footprint file, and can be VRML 2.0 (.wrl) or STEP format. I suggest reading up on the KiCad documentation will help you understand the process.

The normal workflow is:
1) create footprint (.pretty) file from data in the datasheet
2) create or obtain a 3D model in VRML or STEP format.

**Comment by brekee12** [comment]
Thanks for the instructions I succesfully created the parts. The library
structure has to be established, but in the 3D view everything looks OK.

2017-10-15 18:03 GMT+02:00 Bob Cousins <notifications@github.com>:
