### ISSUE TITLE
wrong 3d model

### ISSUE THREAD

**Issue by andres53016** [KiCad/kicad-library#173]
The 3d models Diode_LED_3mm_round_vertical and Diode_LED_5mm_round_vertical In kicad-library/modules/packages3d/Diodes_ThroughHole.3dshapes/ are DO-35 and the LED have own directory.
Can I delete this?
And replace the current 3d model for the mentioned in issue #135

**Comment by CarlPoirier** [comment]
The 3d model path should be placed in a folder named the same as the pretty library. What do you mean by "the LED have own directory" ?

**Comment by michal777** [comment]
@CarlPoirier
The 3d models assigned to the footprints are wrong (DO-35 instead of 5mm led) and the LEDs in Diodes_ThroughHole.pretty are duplicates of the leds that are in LEDs.pretty.
So I think it's good idea to remove the duplicates with wrong models.

**Comment by CarlPoirier** [comment]
Aah I wasn't sure what he meant with the directory issue. Indeed, @andres53016, go ahead and we'll approve your pull request.

**Comment by andres53016** [comment]
Hi I created #178 https://github.com/KiCad/LEDs.pretty/pull/4 https://github.com/KiCad/Diodes_ThroughHole.pretty/pull/7

**Comment by CarlPoirier** [comment]
This issue is fixed. Thanks @andres53016.
