### ISSUE TITLE
I am creating a DC Power Supply in Kicad. I can't able to clear the error in Kicad EESCHEMA. 

### ISSUE THREAD

**Issue by Nellairaja** [KiCad/kicad-library#1744]
![error](https://user-images.githubusercontent.com/32923241/31758436-43e958c0-b462-11e7-8789-eb59ba076502.png)
![schematic diagram](https://user-images.githubusercontent.com/32923241/31758437-444dd250-b462-11e7-9d39-b89feb8b26ef.png)
If you know how to clear a error. I need to create a footprint for this Dc power supply project. To create a DC POWER SUPPLY in PCB 
Please reply me to this email id : rajatvl27@gmail.com

**Comment by antoniovazquezblanco** [comment]
This is probably more suited to be posted in the forums and not library issues but anyways:

From your image you have not properly connected many components. Delete the wires with conflicts and try to wire things from the end of the pin. I've highlighted the conflicting points I could see in your image:
![imagen](https://user-images.githubusercontent.com/304193/31759613-42d8e0a4-b4b2-11e7-9bc7-4f10e36bf312.png)

**Comment by gauravjuvekar** [comment]
@Nellairaja  Please post this to https://forum.kicad.info/

**Comment by Nellairaja** [comment]
In this project I am try to clear the error and reconnect the circuit with
wire... But the wire was not connected properly. I didn't know what is the
reason.... Take me how to connect the circuit with the wire tool

**Comment by poeschlr** [comment]
Please post your question over at the user [forum](https://forum.kicad.info/). (You don't even need to create a new account. You can use single login with your github, facebook, google, ... account.)

**Comment by Nellairaja** [comment]
please help me to clear the above error in this project.

**Comment by poeschlr** [comment]
Again this is the wrong platform for this. Is there a reason why you think the forum is not for you?

The forum has more powerful tools for people who want to help you. 

There is also a more diverse group of people available to help you. 

This issue is mostly only seen by library maintainers. Which means you spam our wall instead of reaching the people who can help you.

**Comment by sandhan26** [comment]
@Nellairaja you might have accidentally altered the grid size, while working with the wires. Thats why they are not connecting. 

The best thing for you would be, start fresh, and be mindful of not changing the grid size, don't rush.
Trust me, i used to get a lot that.
