### ISSUE TITLE
Where to place Particle P1 module

### ISSUE THREAD

**Issue by antoniovazquezblanco** [KiCad/kicad-library#1751]
In which library should I place the symbols and footprint that I am about to make for the Particle P1 module?

Thank you

**Comment by gauravjuvekar** [comment]
RFSolutions for the symbols and RF_modules (https://github.com/KiCad/RF_Modules.pretty) for the footprints seem to be the most appropriate.

**Comment by antoniovazquezblanco** [comment]
👍 

Will start working on it! Thanks!
