### ISSUE TITLE
Discret:TO92DGS has pins ordered SGD

### ISSUE THREAD

**Issue by strykeroz** [KiCad/kicad-library#176]
Hi,

Please correct me if I'm wrong, but this appears to have D & S pins swapped.
![to92dgs](https://cloud.githubusercontent.com/assets/1422307/7156862/81efb39a-e3ad-11e4-81e0-edace415ba26.JPG)

Geoff

**Comment by ricardocrudo** [comment]
Where does this footprint come from? Which .pretty directory?

**Comment by strykeroz** [comment]
According to my library table, ${KIGITHUB}/Discret.pretty should be the source.
This is from a recent launchpad build, 2015-04-09 BZR5589

**Comment by ricardocrudo** [comment]
It's named as DGS, since the square pin is the first, it seems right, though, it's violating some KLC rules.

**Comment by michal777** [comment]
TO-92 packages that meet KiCad Library Convention rules are in: Housings_TO-92.pretty
This one is going to be removed (when somebody will find some time to sort out Discret.pretty).

**Comment by strykeroz** [comment]
The schematic symbol for the BS170 MOSFET in the transistors library has pads D-G-S however all TO-92 packages in Housings_TO-92.pretty currently have pads 1-2-3.  Choosing any of those footprints results in no ratsnest to the BS170 footprint.

**Comment by michal777** [comment]
This is because schematic symbol is also bad and should be improved to use standard numbering.

**Comment by ricardocrudo** [comment]
The BS170 that I have here, from transistors lib, is numbered from 1 to 3. Did you install your libraries manually or from your distro repo (in the case that you are using linux)?

**Comment by strykeroz** [comment]
Interesting.  This was a version made last week using the repo through kicad-winbuilder.  I'll update and report here if it changes.

**Comment by ricardocrudo** [comment]
Is that kicad-winbuilder for libraries or the KiCad program?

**Comment by strykeroz** [comment]
It downloads everything.  A search for transistors.lib only shows the instances in the source files it has downloaded and the KiCad directory tree it creates.  There are no other copies on this PC.  I will archive the KiCad build I used for the above, and rebuild.

**Comment by strykeroz** [comment]
I archived the existing build to a 7z, deleted the directory and rebuilt.  No errors but the version number curiously remains the same.  As does the component in eeschema:
![capture](https://cloud.githubusercontent.com/assets/1422307/7169450/f3e19bca-e408-11e4-9f02-630fef1be36e.JPG)

**Comment by strykeroz** [comment]
Further, as expected, when importing .cmp into Pcbnew, the following errors:
*** Error: Component 'Q1' pad 'D' not found in footprint 'Housings_TO-92:TO-92_Molded_Wide_Oval' ***
*** Error: Component 'Q1' pad 'G' not found in footprint 'Housings_TO-92:TO-92_Molded_Wide_Oval' ***
*** Error: Component 'Q1' pad 'S' not found in footprint 'Housings_TO-92:TO-92_Molded_Wide_Oval' ***

**Comment by ricardocrudo** [comment]
That's odd. Could you paste your netlist and cmp files at pastebin?

**Comment by keruseykaryu** [comment]
@strykeroz: Please remove project library cache, reopen schematic, recreate netlist and pass through CvPcb again.

**Comment by strykeroz** [comment]
@keruseykaryu you are correct.  This is now solved as being my project library cache issue.
