### ISSUE TITLE
Two Bosch libs with different names; causes conflict on Windows

### ISSUE THREAD

**Issue by bobc** [KiCad/kicad-library#1762]
There are two libs for same manufacturer with different names. On Windows, library names are not case-sensitive, so these libs conflict.

Proposal:
- move parts from bosch.lib to Bosch.lib
- remove bosch.lib/.dcm

**Comment by ppelleti** [comment]
This is a problem on Mac OS X as well.  It causes git to always think that Bosch.lib/.dcm are modified, so it will be difficult to make any contributions downstream of this commit until it is resolved.

**Comment by sandhan26** [comment]
I have a Linux system. I can move the only component 'BMF055' present in 'bosh' library to 'Bosh' library, and delete the 'bosh'. I will take time until evening to fix it.

**Comment by SchrodingersGat** [comment]
PR here - https://github.com/KiCad/kicad-library/pull/1767

**Comment by bobc** [comment]
Yes, I am also stuck with submitting PRs due to this issue!

**Comment by jkriege2** [comment]
merged the PR

**Comment by bobc** [comment]
Just as I was typing, thanks! 👍
