### ISSUE TITLE
USB symbols and footprints

### ISSUE THREAD

**Issue by ricardocrudo** [KiCad/kicad-library#177]
I'd like to suggest a little change in the USB symbols. Currently there are 3 symbols:
* USB
* USB-MICRO-B
* USB-MINI-B

My suggestion is use 3 USB symbols: 
* USB_A
* USB_B
* USB_OTG

The USB_A/USB_B symbols would be a simple square with 5 pins: VCC, D-, D+, GND and Shield, numbered 1 to 5. The only difference between them would be the VCC pin type (power in/power out).

The new USB_OTG would be a simple square with 6 pins: VCC, D-, D+, ID, GND and Shield, numbered 1 to 6. It could be used to USB mini or micro.

If you agree with this changes I can pull request them including the changes in the footprints.

**Comment by keruseykaryu** [comment]
I have no objections.

**Comment by CarlPoirier** [comment]
It's a good idea.

**Comment by CarlPoirier** [comment]
Thanks Ricardo.
