### ISSUE TITLE
Incorrect pin electrical type on 74LS30.

### ISSUE THREAD

**Issue by 117L7** [KiCad/kicad-library#1787]
The 74LS30 from the 74xx library has the output pin (8) marked as an input pin. This causes ERC failures.

KiCad 4.0.7 for OS X.

**Comment by SchrodingersGat** [comment]
@117L7 can you submit a PR to address this issue? This will be the quickest path to fixing :)

**Comment by 117L7** [comment]
Sure, how would I do that?

**Comment by SchrodingersGat** [comment]
http://kicad-pcb.org/libraries/contribute/

If this all seems too much for you, perhaps someone will have time to make the fix for you.. But, if you are willing to learn, extra contributors are *always welcomed!*

**Comment by bobc** [comment]
I think I already fixed this. Did you check the latest version of Logic_74xx ? It looks correct to me.

**Comment by 117L7** [comment]
I downloaded kicad-library-master, it looks like the libraries have been
reorganized compared to the 4.0.7 distribution.

I'll give Logic_74xx a try later today.

**Comment by poeschlr** [comment]
Yes we have already started the preperation for the v5 release. You might want to use some older commit.
@jkriege2, @SchrodingersGat should we tag the last commit before we started with the reorganization?

**Comment by 117L7** [comment]
I tried Logic_74xx, but the problem now is the symbols are a smaller size (which is a good thing), and the shrinkage apparently caused all the devices to disconnect from the nets. I didn't expect this would happen.

I uploaded some screen shots before/after, from the original 2 to now 299 ERC errors, so the testing is inconclusive.

I was able to restore by removing the library and using the schematic redraw button.

![screen shot 2017-11-02 at 11 23 33 am](https://user-images.githubusercontent.com/33296813/32343951-7352976e-bfc2-11e7-8970-1ace6eedc606.png)
![screen shot 2017-11-02 at 11 28 08 am](https://user-images.githubusercontent.com/33296813/32343953-73744742-bfc2-11e7-8608-52074daf011c.png)

**Comment by poeschlr** [comment]
Not only the size did change. We also moved the power pins to a separate unit. (They where invisible pins placed at every unit in the old lib.)

This is why we will release this stuff only for the v5 release. Users will expect massive changes on a major release so the surprise will not be that bad.

**Comment by poeschlr** [comment]
If the electrical types are still wrong please reopen this over at https://github.com/KiCad/kicad-symbols. Regarding recising: you will need to accept these changes as the new lib is intended for a new major release and we allow major changes there. We will try to keep the lib as stable as possible during the next stable release cycle.
