### ISSUE TITLE
SOT-23 footprints in Diodes_SMD appear to have incorrect spacing.

### ISSUE THREAD

**Issue by stambaughw** [KiCad/kicad-library#179]
I was reviewing a board layout that I just did and noticed that the spacing between pins 1 and 2 is too narrow for footprints Diode_SOT23 and Diode_SOT23_handsoldering in the Diodes_SMD library.  The current spacing is 1.6mm but every document I could find specifies 1.9mm.  Both footprints should be reviewed for accuracy.

**Comment by ricardocrudo** [comment]
Indeed. I can fix this in the pull request: KiCad/Diodes_SMD.pretty#6

**Comment by ricardocrudo** [comment]
I just remember that SOT-23 is duplicated in KiCad/Housings_SOT-23_SOT-143_TSOT-6.pretty. This last one contain has the footprint with the correct values.

**Comment by ricardocrudo** [comment]
@michal777 @CarlPoirier, which one should be removed?

**Comment by stambaughw** [comment]
On 4/22/2015 11:21 AM, Ricardo Crudo wrote:
> I just remember that SOT-23 is duplicated in
> KiCad/Housings_SOT-23_SOT-143_TSOT-6.pretty. This last one contain has
> the footprint with the correct values.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KiCad/kicad-library/issues/179#issuecomment-95233949>.
> 

That's fine but we should probably remove the incorrect footprints for
the Diodes_SMD library.

**Comment by stambaughw** [comment]
On 4/22/2015 11:36 AM, Ricardo Crudo wrote:
> @michal777 <https://github.com/michal777> @CarlPoirier
> <https://github.com/CarlPoirier>, which one should be removed?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KiCad/kicad-library/issues/179#issuecomment-95239821>.
> 

Diode_SOT23 and Diode_SOT23_Handsoldering should both be removed from
the Diodes_SMD library.

**Comment by CarlPoirier** [comment]
Thanks Wayne for reporting this. Let's remove the footprints from
Diodes_SMD and keep the ones from Housings_SOT-23_SOT-143_TSOT-6.pretty.

**Comment by CarlPoirier** [comment]
Creating a _HandSoldering version from the correct footprint would be great
however. Else we lose that footprint.

Ricardo, I will approve your pull requests tonight.

**Comment by ricardocrudo** [comment]
@CarlPoirier Housings_SOT-23_SOT-143_TSOT-6.pretty has a _HandSoldering version to SOT-23 as well.

**Comment by CarlPoirier** [comment]
Indeed, haha! All is well, then.

**Comment by CarlPoirier** [comment]
The duplicates have been removed.
