### ISSUE TITLE
atmel.lib has some old parts with conflicting names

### ISSUE THREAD

**Issue by bobc** [KiCad/kicad-library#1795]
There are two parts named "ATmega32U4" and "ATmega32U4-AU" (case sensitive). I think these have been replaced with same name but in upper case. The duplicate names cause a conflict in some KiCad dialogs (e.g. part browser).

Proposed fix : remove the old duplicates "ATmega32U4" and "ATmega32U4-AU" (case sensitive)

**Comment by SchrodingersGat** [comment]
Can you submit a fix? Your solution sounds sensible.

**Comment by poeschlr** [comment]
@SchrodingersGat, @bobc what is the state of this?

**Comment by bobc** [comment]
I thought that a PR had been submitted, but I can't find it. The problem seems to be still there.

**Comment by poeschlr** [comment]
Created an issue over at the new repo
