### ISSUE TITLE
Broken datasheets for NXP logic ICs

### ISSUE THREAD

**Issue by bobc** [KiCad/kicad-library#1802]
NXP logic products are now transferred to Nexperia, so a lot of datasheet URLs have stopped working.  :)
It should be possible to fix with a global search/replace.

**Comment by poeschlr** [comment]
Well as you mentioned in some other issue, datasheet links will be hard to keep up to date. I reopened this in the new repo anyways. New issue https://github.com/KiCad/kicad-symbols/issues/183
