### ISSUE TITLE
Pin header wrong names by KLC?

### ISSUE THREAD

**Issue by hildogjr** [KiCad/kicad-library#1824]
I was doing a schematic and linking the footprints. So was I quite annoying found the correct pin header.

Now reading the [KLC Conventions for Connectors](http://kicad-pcb.org/libraries/klc/) I realize that that name of the `Pin_Header` library is in the opposite order.

By this standardization I understood that, for example, the `Pin_Header_Straight_2x20_Pitch2.54mm`, `Pin_Header_Angled_2x20_Pitch2.54mm` and `Pin_Header_Straight_2x20_Pitch2.54mm_SMD` would be called `Pin_Header-2x20_Pitch2.54mm_Vertical` (or even without `_Vertical` because is the most common), `Pin_Header-2x20_Pitch2.54mm_Horizontal` and `Pin_Header-2x20_Pitch2.54mm_SMD`. Am I correctly?

Even in documentation, the example is `PinHeader_1x10_P2.54mm_Drill1.25mm_Horizontal`.

**Comment by poeschlr** [comment]
The pin headers have already been renamed in the new repo. The old repo is declared a legacy repo and will be kept in its current state such that kicad v4 does not break.

New footprint repo: https://github.com/KiCad/kicad-footprints
