### ISSUE TITLE
Missalignment on SOT-23 and SOT-23_Handsoldered

### ISSUE THREAD

**Issue by mmFooD** [KiCad/kicad-library#1836]
The 3D-models on the SOT-23 and SOT-23_Handsoldered modules are missaligned by 90 deg.

**Comment by Shackmeister** [comment]
This has been reported quite a few times by now.. Please update your footprints and 3D models..

**Comment by mmFooD** [comment]
Should've looked through the closed issues. Updated footprints yesterday, but of course the 3D models needs to be updated as well. Impressed by the quick response, Thanks!
