### ISSUE TITLE
dc-dc.lib not working with kicad 4.0.7

### ISSUE THREAD

**Issue by aurel32** [KiCad/kicad-library#1838]
Commit d89bebae7594f3ecf19027510e1e569798de691e made many format changes to the dc-dc library and this causes the description, the keywords and the documentation fields to be empty for all devices in this library. It seems that just downgrading the version in the header from 2.4 to 2.3 fixes the issues, but I don't know if there other side effects.

**Comment by jkriege2** [comment]
I posted a fix: https://github.com/KiCad/kicad-library/pull/1840

**Comment by aurel32** [comment]
Thanks, I confirm the fix works.
