### ISSUE TITLE
Wrong transistor symbols

### ISSUE THREAD

**Issue by bbrandst** [KiCad/kicad-library#1843]
The schematic symbols of some transistors in Transistor.lib are not correct.
For instance, both BF244 and BF245 are actually N-JFETs, but in current Git, BF244 is shown as a bipolar transistor while BF245 is presented as a MOSFET. Possibly other transistors are affected as well.
I'm not quite sure but I think this happened during commit 0b9d383.

**Comment by poeschlr** [comment]
Mistakes are always possible. (We librarians are not all knowing.)

Car to fix it?

**Comment by jkriege2** [comment]
Hi!

I'm already at it (+ some more fixes in that lib) ... might take 1-2 days, but a fix will be posted ;-)

cu
JAN

**Comment by jkriege2** [comment]
fixed in here: https://github.com/KiCad/kicad-library/pull/1844

**Comment by SchrodingersGat** [comment]
Fixed in #1844
