### ISSUE TITLE
SOT-23 and SOT-23_Handsoldering 3D model scaling and rotation issue.

### ISSUE THREAD

**Issue by stambaughw** [KiCad/kicad-library#185]
It appears that someone fixed the scaling and rotation of the SOT-23 3D model but the 3D properties of the footprint were never updated accordingly( see attached image).

![image](https://cloud.githubusercontent.com/assets/5891750/7419040/677d7c7e-ef40-11e4-9b79-b65c1cd2519c.png)

**Comment by michal777** [comment]
Fixed
