### ISSUE TITLE
Library names

### ISSUE THREAD

**Issue by DerekGn** [KiCad/kicad-library#1851]
Hi,

I have a few library parts that I would like to submit to kicad.

**HDC1080**
A Texas Instruments temperature humidity sensor

**RN4871**
A microchip BLE module

**AAT1217ICA** 
A skyworks  Micropower Synchronous Step-Up Converter

I am looking for some hints with respect to naming convention for the libraries before I submit the pull requests.

Following the conventions I have come up with 

Sensor_Temperature_Texas_HDC
Wireless_Ble_Microchip_RN
Regulator_Boost_Skyworks_AAT

Derek

**Comment by poeschlr** [comment]
https://github.com/KiCad/kicad-library/issues/1402

**Comment by DerekGn** [comment]
Thanks

**Comment by SchrodingersGat** [comment]
@DerekGn please note that you should not place symbols in their own libraries.

I would suggest using more generic names such as 

* Sensor_Temperature
* RF_Bluetooth
