### ISSUE TITLE
DXF Import fails with Umlaut in Foldername 

### ISSUE THREAD

**Issue by mrred2k** [KiCad/kicad-library#1853]
I was trying to import DXF files.
This which worked fine in the past. (I fixed the polyline issue with my files)
Bit the import was failing without any error.
Turns out there was a umlaut "ä" in one of the file folders.

Maybe this can be adressed or at least help someone figuring it out.

**Comment by poeschlr** [comment]
This is the repository for the kicad library (symbols and 3d models of version 4 to be exact)
Bug reports should be posted over at the [bug tracker](https://bugs.launchpad.net/kicad)
Questions about problems can be posted at the [kicad user forum](https://forum.kicad.info/)
