### ISSUE TITLE
do ".." equal with "-"

### ISSUE THREAD

**Issue by 243750496** [KiCad/kicad-library#1860]
i mean do the label raw2[0..1] equal with raw2[0-1] equal with raw[20..21] equal with raw(20-21)

and can i use raw2[0..1] with raw2[0-1] or raw[20..21] as a paired label ?? whether it will show an error?

i am a newbee , i hope you can answer my question  with patience 
thx in adv :)

**Comment by SchrodingersGat** [comment]
Hi @243750496 this is a question that would be better addressed over at the [user forums](https://forum.kicad.info/) - this github page is for library maintenance :)
