### ISSUE TITLE
Add generic IC types. 

### ISSUE THREAD

**Issue by wgaylord** [KiCad/kicad-library#1870]
So you can still you KiCAD with out having to learn how to make a new IC for the library if your IC is not i nthe Library.

(Example LM75BD Temperature sensor which is a SO8)

**Comment by bobc** [comment]
Do you mean something like this?

![image](https://user-images.githubusercontent.com/972103/33983243-56fb2c34-e0ab-11e7-8ab5-7e29776b07fd.png)

There used to be some DILxx symbols, but I think they were dropped.

**Comment by bobc** [comment]
Just for fun, I created a library with common IC sizes. 

[IC_Generic.zip](https://github.com/KiCad/kicad-library/files/1559133/IC_Generic.zip)

Btw, issues regarding symbols should probably now go to the new repo https://github.com/KiCad/kicad-symbols

**Comment by poeschlr** [comment]
I close this as we already transferred all symbols over to the new repo. If this is still relevant please reopen it over at https://github.com/KiCad/kicad-symbols
