### ISSUE TITLE
MCU_Microchip_PICxx libraries on git are still using "/" in the partname and footprints

### ISSUE THREAD

**Issue by supyrow** [KiCad/kicad-library#1881]
MCU_Microchip_PICxx libraries on git are still using "/" in the partname and footprints
 i have repaired the files the same way PIC12 was done by replacing (for example) "PICxxxx-I/SO" with "PICxxxx-ISO" on all affected libs and dcm files.  i have gone through each file and changed all names accordingly.  i will make a pull request

**Comment by poeschlr** [comment]
This is the legacy repo. (There will be no more changes to it.)
That stuff should be fixed in the new repo: https://github.com/KiCad/kicad-symbols

If not re open the issue in that repo.
