### ISSUE TITLE
merge CONTRIBUTING.txt into README.md

### ISSUE THREAD

**Issue by ricardocrudo** [KiCad/kicad-library#190]
I'd like to suggest to merge the content of CONTRIBUTING into README file. I think in this way the users can easily see how to contribute to and also the link to KLC will be right on there.

**Comment by CarlPoirier** [comment]
The CONTRIBUTING.txt file has the advantage of being recognized by Github and it shows I believe a warning when you open a pull request or something. We could still put its content or a link to it in the README.md.
