### ISSUE TITLE
Cvpcb in Ubuntu 14.04.2 LTS trusty

### ISSUE THREAD

**Issue by GauravSupal** [KiCad/kicad-library#281]
Hii

I installed kicad in Ubuntu 14.04.2 LTS (trusty) but cannot run cvpcb through the terminal (showing :"The program 'cvpcb' is currently not installed. You can install it by typing: sudo apt-get install kicad")

**Comment by michal777** [comment]
This is library repo, to report a bug or ask a question visit kicad on launchpad.
cvpcb built in eeschema
https://answers.launchpad.net/kicad/+question/268313
