### ISSUE TITLE
SOT-223 3d model is HUGE

### ISSUE THREAD

**Issue by timtashpulatov** [KiCad/kicad-library#300]
Need to apply 0,3937 scaling to XYZ dimensions to display properly

**Comment by michal777** [comment]
It's scaled here: https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/blob/master/SOT-223.kicad_mod
```
  (model TO_SOT_Packages_SMD.3dshapes/SOT-223.wrl
    (at (xyz 0 0 0))
    (scale (xyz 0.4 0.4 0.4))
    (rotate (xyz 0 0 0))
  )
