### ISSUE TITLE
Connectors_JST_* not in templates

### ISSUE THREAD

**Issue by bobc** [KiCad/kicad-library#351]
The Connectors_JST_* repos are not in the template fp-lib-table files. Is that intentional, or should these be added?

**Comment by ricardocrudo** [comment]
@bobc Connectors_JST_* will be moved to https://github.com/KiCad/Connectors_JST.pretty

**Comment by CarlPoirier** [comment]
The Connectors_JST.pretty has been added to the table 6 days ago.
