### ISSUE TITLE
Which <manufacturer>.lib to choose ?

### ISSUE THREAD

**Issue by kinichiro** [KiCad/kicad-library#365]
Hi, I have a question about component library.

- component XYZ was originally manufactured by AAA company
- AAA is acquired by BBB, then component XYZ belongs to BBB, now

In this case, which library should contain XYZ ?
aaa.lib ? bbb.lib ?

I thought if choosing current owner library,
that library will contain many components and grow huge
since acquisitions are so often.

I think big library file that contains many components leads maintenance difficulties.

KLC seems does not have convention about this.

Is there any rule for this issue ?

**Comment by pointhi** [comment]
What type of component is it?

Probably it fit better in one of the component specific libraries instead of the vendor specific ones.

**Comment by kinichiro** [comment]
Hi,

I am thinking about OTA and BBD chip.
OTA might be contained in opamp group.
BBD might be contained in analog group.
Are these choices correct ?

I asked this question since I can not tell which is preferable library.
Is there any rules for this issue ?

Thanks

**Comment by pointhi** [comment]
Hy,

for opamp's ```linear.lib``` and ```analog_devices.lib``` are currently used.

In my opinion ```analog_devices.lib``` should fit for OTA as well as for BBD chips.

**Comment by keruseykaryu** [comment]
@pointhi "In my opinion `analog_devices.lib` should fit for OTA as well as for BBD chips."
If they was manufactured by Analog Devices. This is vendor specific library, not function specific library.

**Comment by pointhi** [comment]
@keruseykaryu thanks, I have forgotten there is also a company named Analog Devices.

Hm, then I would place the OTA chips into ```linear.lib```. For BBD chips I'm unsure if any current library would fit it.

**Comment by kinichiro** [comment]
Thanks.
I thought linear.lib was for Linear Technology,
but it seems for general linear ICs.

**Comment by kinichiro** [comment]
Hi,
According to the recommendation, I did 2 things below.

- added OTA to `linear.lib` and submit PR #384 .
- created new `bbd.lib` for BBD chip and submit PR #386 .

I'll close this issue.
Thanks.
