### ISSUE TITLE
atmel.lib: overlapping pin names in most atxmega symbols

### ISSUE THREAD

**Issue by madworm** [KiCad/kicad-library#367]
![atxmega16a4u-a](https://cloud.githubusercontent.com/assets/343894/12215965/bce9d464-b6d2-11e5-83bc-b1a106d7b4b6.png)

https://forum.kicad.info/t/eeschema-pin-names-overlapping-for-parts/2015

**Comment by keruseykaryu** [comment]
So, you have to take things in your hand. It's the best thing you can do.

**Comment by poeschlr** [comment]
This is related to https://github.com/KiCad/kicad-symbols/issues/187
