### ISSUE TITLE
Changed wording of footprint rules to be more understandable 

### ISSUE THREAD

**Issue by DavidMenting** [KiCad/kicad-library#381]
Unfortunately there is no way to do a pull request for a wiki. I've changed the wording of the footprint rules so that they are more easily understandable.

Please have a look at the following commit:
https://github.com/nutbolt/kicad-library-wiki/commit/5f8dac16b948f4b0b9b002651ae64fa3344925a0
- explains courtyard in a few words
- replaced the word 'superposed' by 'on top'

**Comment by SchrodingersGat** [comment]
@DavidMenting looks like this one got lost, I am closing this as it has now been long superseded by the new KLC - http://kicad-pcb.org/libraries/klc/
