### ISSUE TITLE
Add numbers to the KLC headings in wiki

### ISSUE THREAD

**Issue by kasbah** [KiCad/kicad-library#398]
I was trying to see what rules where being checked by check_kicad_mod.py and the lack of numbering was making it a bit confusing, I added them in a fork of the wiki but there is no way to do Github PRs for the wiki.

https://github.com/kasbah/kicad-library-wiki/commit/8448ca6d3a08aa28cf5e5972d327e4bb85ab7516

**Comment by CarlPoirier** [comment]
Fixed, thanks for pointing that out.
