### ISSUE TITLE
3D model for a 7mm resistor

### ISSUE THREAD

**Issue by Fat-Zer** [KiCad/kicad-library#403]
Currently there is no model for a 7mm resistor in the library. IMHO this is a quite major loss...

If nobody is going to fix it in a couple of days, I'm going to pull-request one, but I will make it with FreeCAD rather than wings.

Any comments / any good ready-to-use models / other volunteers?

**Comment by Fat-Zer** [comment]
Ok, I've done a model... I was a bit confused what resistor is suitable for the "Resistors_ThroughHole:Resistor_Horizontal_RM7mm" footprint. I've decided to use dimensions for SFR16S from this datasheet: http://www.vishay.com/docs/28722/sfr16s25.pdf.

![resistor-7mm](https://cloud.githubusercontent.com/assets/1060057/13261898/53a78770-da73-11e5-855b-438393f1de3e.png)

It differs from other resistors, by obvious reasons, but IMHO It looks a bit better.

**Comment by Shackmeister** [comment]
@Fat-Zer hi, im case this is not relevant any more could you please consider closing this issue? :)

**Comment by Fat-Zer** [comment]
Closing due to outdated as mentioned on https://github.com/KiCad/kicad-library/pull/408.
