### ISSUE TITLE
Probably wrong alias: LM101H

### ISSUE THREAD

**Issue by Fat-Zer** [KiCad/kicad-library#406]
The linear library has a probably wrong alias for CA3130. I found no information on LM101H that may match the CA3130 leads: nor in datasheets nor in stores. I suppose it's just a mistake. If there are no arguments for keeping it, I would like to propouse to remove it out of cleaning thoughts.

**Comment by PiotrCzCc** [comment]
I agree. This is incorrect to make alias to LM101H. I found only LM101A/LM201A/LM301A.
Corrected lib is uploaded.

**Comment by diggit** [comment]
Removed, closing.
