### ISSUE TITLE
wrong pad numbering for SolderWirePad... footprints in modules/Wire_Pads.kicad_pcb

### ISSUE THREAD

**Issue by mumme74** [KiCad/kicad-library#417]
There seems to be a error with SolderWirePad footprints where there are multiple pads in the footprint, all pads are number 1, should probably be in sequence like all other footprints

modules/Wire_Pads.kicad_pcb

**Comment by keruseykaryu** [comment]
This question was discussed (I couldn't find it now). This kind of numeration is intended by the author.
These footprints are used for soldering multiple wires connected to a single point (net) on the board. This solution is widely used eg. in PC power units.

**Comment by mumme74** [comment]
ok I thought it was a error.
No problem, I can choose another footprint
