### ISSUE TITLE
Power_Packages_SMD.pretty

### ISSUE THREAD

**Issue by SchrodingersGat** [KiCad/kicad-library#437]
Hi all,

I note that Power_Packages_SMD.pretty has been moved to:

https://github.com/wiebus/Power_Packages_SMD.pretty

Is there a new .pretty repo for SMD power MOSFETs etc?

**Comment by CarlPoirier** [comment]
Hi Oliver,

How about TO_SOT_Packages.pretty?

**Comment by SchrodingersGat** [comment]
Ok, thanks :)
