### ISSUE TITLE
Issue in Cvpcb footprint library path (https://github.com/KiCad)

### ISSUE THREAD

**Issue by GauravSupal** [KiCad/kicad-library#440]
Hi,

I found some issue in CvPcb footprint library, here some footprints are missing eg: https://github.com/KiCad/Housings_SOT.pretty and few more. Please help me out.

**Comment by Fat-Zer** [comment]
Against Housings_SOT see this: https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/issues/1

Note that it's likely wrong that they are still referred here e.g. in template/fp-lib-table.for-*

**Comment by CarlPoirier** [comment]
Housings_SOT has been marked as deprecated on August 4 and removed on November 15. If you use the Github plugin to have the latest and greatest footprints, it's great, but you need to keep your fp-lib-table up-to-date!! You can get it in the templates folder or use the wizard in Pcbnew. First, clear the table, then in the wizard, select Github repository and just use "https://github.com/KiCad" as the URL. Then select all .pretty repos.

**Comment by GauravSupal** [comment]
Thanks. It is working now. But still some library was missing after reading netlist in PCBnew.
