### ISSUE TITLE
Wrong pin description for XMega C4

### ISSUE THREAD

**Issue by Koot3391** [KiCad/kicad-library#443]
The XMega C4 eschema part has the USART functions labeled for the wrong pins. This is from the current data sheet:
PC0 10 OC0A OC0ALS SDA
PC1 11 OC0B OC0AHS XCK0 SCL
PC2 12 OC0C OC0BLS RXD0
PC3 13 OC0D OC0BHS TXD0

**Comment by diggit** [comment]
Confirmed, PD2 is wrong too. Symbols ATXMEGA[16,32]C4-*
@keruseykaryu did you use some script to assign alternate functions to ATXMEGA MCUs?
Commits c323fc3630c0a74f522870bc75596c40ee4a5faa and f77db2ade8bdf240ba7a2060b2dea7c8662e1a14

**Comment by keruseykaryu** [comment]
I don't believe in scripts during creating my libraries. So it is my mistake.

**Comment by diggit** [comment]
@keruseykaryu can you recheck those symbols and do PR with fix?

**Comment by keruseykaryu** [comment]
I'm sorry Patrik, but I have to deny your request. It need to do more than just correct mistakes. Currently, I have neither the time nor the desire for it.

**Comment by keruseykaryu** [comment]
Going to the compromise, I can only do this in this way.

**Comment by Shackmeister** [comment]
@koot3391 do you know if this has been fixed since? In case not, can you please make a PR for it?

**Comment by poeschlr** [comment]
As this repo will be archived soon in preparation for the v5 release, i transferred it over to the new repo https://github.com/KiCad/kicad-symbols/issues/188
