### ISSUE TITLE
Broken library ir

### ISSUE THREAD

**Issue by diggit** [KiCad/kicad-library#467]
Library of international Rectifier is real mess. Wrong descriptions, missing keywords... PbF suffix does not belong here.
Symbols need some rework. IR211* symbols have outputs on left and inputs on right - exact opposite of KLC 3.5.

**Comment by El3ctr0nic** [comment]
I can fix IR lib. Remake mosfet driver using pull request 387 style drawing.
Pls check my pull request and give me some feedback.
Regards

**Comment by diggit** [comment]
PR #387 merged. It will be great if you can take care of it. BTW I don't think those IR21* are similar to your IRS2181\*.

**Comment by El3ctr0nic** [comment]
I find some way to fit it ;) Give me 2-3 days
