### ISSUE TITLE
SOIC-14_N and SOIC-14_W footprints mistakenly interchanged!

### ISSUE THREAD

**Issue by joseangeljimenez** [KiCad/kicad-library#49]
Hello,

It seems like the modules (footprints) for SOIC-14_N (narrow) and SOIC-14_W (wide) are mistakenly interchanged. I mean,
- The wide footprint is stored as SMD_Packages:SOIC-14_N
- The narrow footprint is stored as SMD_Packages:SOIC-14_W

If confirmed, this is a serious bug which may end into unusable PCBs!
Could somebody check it?

Thank you,
José Ángel Jiménez

**Comment by Shackmeister** [comment]
@joseangeljimenez would you mind if I close this? It's probably pretty deprecated by now :)

**Comment by Shackmeister** [comment]
@joseangeljimenez hi Ill close this up due to the inactivity, if you want to continue you can simply reopen it
