### ISSUE TITLE
Which library chose for TCA9534 I2C I/O Expander

### ISSUE THREAD

**Issue by penoud** [KiCad/kicad-library#505]
Could you help me to chose the right library for the TCA9534 IC
datasheet : http://www.ti.com/lit/ds/symlink/tca9534.pdf

**Comment by diggit** [comment]
I suggest *interface*, but *texas* is possible too.
Start from PCF8574 symbol, preserve identical function pins placement, as much as possible.

**Comment by penoud** [comment]
Thank you
