### ISSUE TITLE
KLC Rules 3.1 and 3.2 conflict

### ISSUE THREAD

**Issue by inio** [KiCad/kicad-library#520]
> 3.1.  Using a 100mils grid, pin **ends and origin** must lie on grid nodes (IEC-60617).
> 3.2.  *[..]* Large pin numbers can be accomodated by incrementing the width in steps of **50mil**.

Clearly if you increment the pin length by 50mil (for example to 150mil) you can't have both the end and origin on a 100mil grid.

**Comment by diggit** [comment]
Only connection **end** of pin matters, it must lie on 100mil grid. **Origin** [0;0] of coordinate system must lie in 100mil grid too.
It simply means, you have to place your pin connection end on [ a*0.1 ; b*0.1 ] coordinates and not sth like [ a*0.1+0.05 ; b*0.1+0.05 ] (still on 100mil grid, but not together with origin [0;0])

At least I understand it this way.

**Comment by inio** [comment]
Aaaah, that reading makes so much more sense!

**Comment by diggit** [comment]
If it's clear, I think, I can close this issue...
