### ISSUE TITLE
Sensors:LM35 missing FP filters and descripotin

### ISSUE THREAD

**Issue by diggit** [KiCad/kicad-library#566]
Symbol **LM35** in Sensor library is specific for TO220 package. (Found out the hard way**):**
Missing description and FP filters leads to incorrect conclusion of matching pinout for all 3pin variants.

Design should be improved too. **MCP9700T-H/TT** looks like the way to go.

Feel free to create PR with fix, I am busy now.

**Comment by SchrodingersGat** [comment]
@diggit PR is here https://github.com/KiCad/kicad-library/pull/567
