### ISSUE TITLE
Library descriptions of ""The way you like them"??

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-library#590]
The descriptions in the fp-lib-table files seem... not what would be desired. Check out the values of the descr keys in the kicad-library/template/fp-lib-table* files. In fp-lib-table.for-eagle-6.4.0 many of them are empty strings, but the other 3 table files have many libraries with a description of "The way you like them.".

Is this really the desired library descriptions? It seems a more useful string, which a few libraries do have, would be far more helpful to the user and less silly.

If this is a change that needs to be made, and there's already a description paradigm, I'm happy to update the table files as time allows. If there's not already a paradigm, I can take a look at the library contents and suggest a scheme.

**Comment by SchrodingersGat** [comment]
@evanshultz good point, this is a pretty useless description. I have made a start at improving the descriptions. Feel free to contribute with descriptions for lines that I have not fixed yet.

https://github.com/KiCad/kicad-library/pull/593
