### ISSUE TITLE
STM32F378xx family schematic symbols

### ISSUE THREAD

**Issue by mpkopec** [KiCad/kicad-library#650]
Dear Librarians,
I would like to use one of the uCs fromt the mentioned family. They, although, are enormous (see below). Is it really necessary to list every single function of a pin in such situation? The symbol does not even fit on an A4 paper size schematic! Maybe we should introduce some kind of a KLC rule regarding pin descriptions in uCs, maybe dividing uCs into banks, like FPGAs. I'm open to suggestions, and afterwards I could do some changes to this family. What do you think?

PS. At a first glance I would remove those timer related descriptions and leave only more schematic-relevant ones like digital buses.

![stm32f378xx](https://cloud.githubusercontent.com/assets/8792915/17814718/6fbd98e2-6631-11e6-8508-3dd3b9fa77f2.png)

**Comment by SchrodingersGat** [comment]
AFAIK @ObKo generated these with a script which pulls out all the pin names, resulting in the long-run-of-text-pin-naming.

A4 is getting rather large! @ObKo would it be possible to clip the names to the primary/secondary/tertiary functions?

**Comment by poeschlr** [comment]
A lot of MCU symbols show this problem. This needs to be fixed over in the new repo.
See https://github.com/KiCad/kicad-symbols/issues/187
