### ISSUE TITLE
Bug in Print Option

### ISSUE THREAD

**Issue by adithyaselv** [KiCad/kicad-library#656]
Hi,
Choosing Multiple layers to print in a same page in the print option results in printing of the same plot with all details N times (where N is the Number of layers we select). 

Thanks

**Comment by reportingsjr** [comment]
Are you talking about in kicad? If so you should report a bug at the launchpad bug tracker (https://bugs.launchpad.net/kicad).

**Comment by adithyaselv** [comment]
Hey yes ! Thanks I will post it over there 👍
