### ISSUE TITLE
TO-18 model pin 1 tab orientation is incorrect.

### ISSUE THREAD

**Issue by stambaughw** [KiCad/kicad-library#726]
I was working on a board and discovered that the pin 1 indicator tab on the TO-18 3D model does not match the footprint silk screen.  According to the documentation that I have seen, it appears that the footprint silkscreen orientation is correct.

![image](https://cloud.githubusercontent.com/assets/5891750/18888662/4a085736-84c7-11e6-9cc7-a9e5e6877419.png)

**Comment by diggit** [comment]
Thanks, confirmed, model has tab on incorrect position.

If you have some 3D modelling skills, we are open for fixes. Current 3D model looks bad anyway.
Otherwise, I can take a look on it, not sure when.

**Comment by jkriege2** [comment]
I made a small fix:
https://github.com/KiCad/kicad-library/pull/734

**Comment by stambaughw** [comment]
Look great!  Thank you for the quick response.

Cheers,

Wayne

**Comment by jkriege2** [comment]
new 3D models are available now (https://github.com/KiCad/kicad-library/pull/734 merged), footprints still need to be merged (https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/12)!

Best,
JAN

**Comment by SchrodingersGat** [comment]
Ok to close this one @stambaughw ?

**Comment by SchrodingersGat** [comment]
New footprint and 3D model have been merged

**Comment by jkriege2** [comment]
This should be fixed now also with the new footprints https://github.com/KiCad/TO_SOT_Packages_THT.pretty/pull/14
