### ISSUE TITLE
Question on changes in library

### ISSUE THREAD

**Issue by jkriege2** [KiCad/kicad-library#741]
what happens if I change a symbol in the library in a way that breaks backward compatibility (e.g. change pins, move pins etc.)? Is that OK, or does KiCAD rely on having an unchanged symbol in the main lib? An example would be exchanging the 45 tilted and horizontal buttons:
![buton_switch_symbols](https://cloud.githubusercontent.com/assets/11967523/19210934/c17c2d8a-8d30-11e6-9216-b29ea30e00b2.png)

I'm also thinking e.g. about changing the order of pins in an IC, or making pins unhidden (see e.g. the TLC7555=NE555 symbol here https://github.com/KiCad/kicad-library/pull/737 which has VCC+GND unhidden and therefore no longer automatically tied to VCC/GND)?

Also: What happens if we delete a symbol from the lib?

As far as I've seen so far, the components are only saved in the `-cache.lib` libraries and not in the schematic file itself. Correct?

Best,
JAN

**Comment by SchrodingersGat** [comment]
Any symbols you use are stored in the local project files, yes. I think that is is mostly fine to make non-compatible changes to the library as long as they are improvements - we'd take this on a case-by-case basis.
