### ISSUE TITLE
sot89-5 3d dimension

### ISSUE THREAD

**Issue by fastlink30** [KiCad/kicad-library#81]
3d part of sot89-5 is much more big then component footprint

**Comment by CarlPoirier** [comment]
OK, it seems some other parts are affected as well, according to @stambaughw :

SMD_Packages/SOT-23-6.wrl
SMD_Packages/SOT-23-5.wrl
SMD_Packages/SOIC-14_N.wrl
Diodes_SMD/Diode-SMA_Standard.wrl

**Comment by CarlPoirier** [comment]
It looks fine to me. Can you check again?

**Comment by fastlink30** [comment]
tryed but for me is the same, nothing changed

**Comment by CarlPoirier** [comment]
Can you link me to the exact footprint you are using?

**Comment by CarlPoirier** [comment]
The issue has been confirmed to not exist anymore with the most recent revision of kicad-library and the latest footprints.
