### ISSUE TITLE
power/-12VA symbol is unfilled

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-library#821]
In the power library, the positive voltage symbols are an open arrow and the negative ones are a filled arrow. Except for -12VA. It's an open arrow.

Should all negative voltage plumbing symbols be filled? If so, I'll happily fix and create a PR.

**Comment by SchrodingersGat** [comment]
I think that filling it is a good idea to differentiate from the +V symbols.

**Comment by evanshultz** [comment]
Addressed with PR#822.
