### ISSUE TITLE
KLC text anchor proposal

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-library#848]
[KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) does not specify how and where text should be located or justified. From seeing many library parts and the changes being made (like the huge update from @jkriege2), it seems the following is the correct convention:

`Vertically-oriented symbols have text placed to the right of the symbol which is left-justified. Horizontally-oriented symbols have text above and below the symbol which is center-justified.`

This would also be relatively simple verify in checklib.py as the X- or Y-location and justification are easy to parse.

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 @poeschlr Submitting for consideration in KLC 2.1...

**Comment by poeschlr** [comment]
I think text fields are auto placed by eeschema. (In my neither position nor justification of the text fields in the symbol editor has been taken into account by eeschema)

My test in kicad nightly from october last year:
![screenshot from 2017-04-10 19-50-22](https://cloud.githubusercontent.com/assets/18327350/24875147/7120bc1a-1e27-11e7-987c-264f577ec318.png)

![screenshot from 2017-04-10 19-50-15](https://cloud.githubusercontent.com/assets/18327350/24875148/71214d2e-1e27-11e7-9ab8-7476d0ac2b3a.png)

**Comment by poeschlr** [comment]
My second test:
![screenshot from 2017-04-10 20-14-57](https://cloud.githubusercontent.com/assets/18327350/24876095/b2adfe06-1e2a-11e7-8d9f-65d708ac449b.png)

**Comment by Gasman2014** [comment]
This is particularly irksome as the default power connections are to the top of the component and this is exactly where the RefDes and name are auto moved to - wherever they happen to be placed in the original library.

![el7202cn](https://cloud.githubusercontent.com/assets/8401593/24877039/c2857d2c-1e25-11e7-9605-79ca8063cc6a.png)

![screen shot 2017-04-10 at 19 41 25](https://cloud.githubusercontent.com/assets/8401593/24877028/bcdfd55c-1e25-11e7-8a1b-8fc2484ed643.png)

**Comment by SchrodingersGat** [comment]
This is probably worth raising as a [bug-report](https://bugs.launchpad.net/kicad) - the logic that governs the auto-placement of text fields needs serious improvement.

**Comment by evanshultz** [comment]
I submitted a very brief bug pointing back to this issue at https://bugs.launchpad.net/kicad/+bug/1682496.

**Comment by SchrodingersGat** [comment]
@evanshultz I am closing this due to long time without comment. Please reopen if you feel it is not answered.
