### ISSUE TITLE
KLC-rule 3.9

### ISSUE THREAD

**Issue by jkriege2** [KiCad/kicad-library#883]
I would also suggest a change of rule 3.9:

> 3.9 For components with a single default footprint, footprint field is filled with valid entry of the format "Footprint_Library:Footprint_Name" and is set to invisible.

I would propose:
> 3.9 or components with a single default footprint, footprint field is filled with valid entry of the format "Footprint_Library:Footprint_Name" and is set to invisible. **In addition a proper footprint filter has to be defined.**

Best,
JAN

**Comment by SchrodingersGat** [comment]
See https://github.com/KiCad/kicad-library/issues/879

**Comment by SchrodingersGat** [comment]
Footprint filters have now been added to #879
