### ISSUE TITLE
new KLC rule 3.10/3.11/3.12 for footprint filters

### ISSUE THREAD

**Issue by jkriege2** [KiCad/kicad-library#884]
Hi again!

In my experience the footprint filters are a real mess and nowhere defined properly. SO I would propose a new rule:

> 3.10 Whenever possible footprint filters should be set that allow to match all packages that can be used for a symbol (also e.g. different types of packages with the same pinout, such as SOIC-8, TSSOP-8, DIP-8 ...). The footprint filters should follow these rules:
>  - FPFilters use wildcards (`*` matches an number of charactzers and `?` to match 0 or 1 character)
>  - FPFilters should end with a `*`-wildcard to allow matching different modifications of a package (e.g. `_HandSoldering` or `_LargePads`)
>  - FPFilters do *not contain the pin count*. It is matched by the pin count filter of KiCAD
>  - FPFilters should match hyphens ... by `?`, e.g. `TO?220?5*` to match a `TO-220-5`
>  - FPFilters should match as much dimension information as possible to be as specific as possible, e.g. `DIP*W7.62mm*` to match `DIP-22_W7.62mm` and not a DIP-22 with different width, or `SOIC*3.9x8.7mm*Pitch1.27mm*` to match `Housings_SOIC:SOIC-14_3.9x8.7mm_Pitch1.27mm`

In addition we should have a rules 3.11 and 3.12
> 3.11 Symbols must have all pins of the package explicitly available. If they are not connected, they should be marked as such, named `NC` and set to be invisible. This is required to allow for the use of KiCAD's pin count filter.

> 3.12 Exposed pads of a device must have their own pin, typically number max. pintcount+1, e.g. pin 9 for a SOIC-8 with exposed pad. The name of this pin is often set to `PAD` or or a name indicating its function, e.g. `GND/PAD`

What do you
 think?

JAN

**Comment by SchrodingersGat** [comment]
I have implemented `3.10` in https://github.com/KiCad/kicad-library/issues/879

I think that `3.11` and `3.12` should be consolidated into a single rule "Pin Numbering" or something like that - and specified as bullet points. There are a number of other rules that could be included regarding pin numbering

**Comment by SchrodingersGat** [comment]
@diggit  both good points - see changes to https://github.com/SchrodingersGat/kicad-library/wiki/KLC

**Comment by SchrodingersGat** [comment]
Closing this as it is dealth with in #879
