### ISSUE TITLE
images to illustrate KLCs

### ISSUE THREAD

**Issue by jkriege2** [KiCad/kicad-library#891]
## Box symbols
![klc_boxsymbol1](https://cloud.githubusercontent.com/assets/11967523/21741296/422db600-d4d1-11e6-8cb6-add28c5f0e75.png)
![klc_boxsymbol2](https://cloud.githubusercontent.com/assets/11967523/22402792/5c441f00-e603-11e6-8114-8e11e8423cce.png)
![klc_boxsymbol3](https://cloud.githubusercontent.com/assets/11967523/21740549/e41f5de8-d4bc-11e6-82fe-1c93c7a62dae.png)

## NC-pins, pin-length
![klc_symbol2](https://cloud.githubusercontent.com/assets/11967523/21740426/2ae70a08-d4ba-11e6-997d-7685352e0e1a.png)

## pin-grouping + left/right
![klc_symbol3](https://cloud.githubusercontent.com/assets/11967523/21740468/6de4ac1a-d4bb-11e6-9a66-3ab1934d9fb7.png)

## pin types
![klc_pintypes](https://cloud.githubusercontent.com/assets/11967523/21740578/91bb3fa8-d4bd-11e6-8a46-7a0d9f92aa6a.png)

## symbol properties
![klc_props](https://cloud.githubusercontent.com/assets/11967523/21740564/25de997e-d4bd-11e6-9d02-3e2e25182403.png)
![klc_footprintfilters](https://cloud.githubusercontent.com/assets/11967523/21740568/4d5b650e-d4bd-11e6-8292-d9b21ba967d6.png)

## symbol anchor
![klc_anchor](https://cloud.githubusercontent.com/assets/11967523/21740583/d44c7ecc-d4bd-11e6-8e2c-e14c267dbf4e.png)

## THT package
![klc_thtpackage](https://cloud.githubusercontent.com/assets/11967523/21740601/a5ba1de8-d4be-11e6-992a-1be9f4ae5175.png)

## SMD package
![klc_smdpackage](https://cloud.githubusercontent.com/assets/11967523/21740615/38f286c2-d4bf-11e6-92ec-295a652e47fd.png)

## footprint properties
![klc_footprintprops](https://cloud.githubusercontent.com/assets/11967523/21740624/6d1b8372-d4bf-11e6-8f79-799d057c721c.png)

**Comment by cvgaviao** [comment]
There is a typo in the description of GND pin of the first image. it is bottom instead top, right?

**Comment by jkriege2** [comment]
@cvgaviao thanks: fixed it!

**Comment by diggit** [comment]
Image 2 shows counter clockwise port ordering, but ports on right side are not. It is (from top) CDE, should be EDC.

**Comment by diggit** [comment]
I am not telling that CCW rule is better, the way it is makes more sense IMO.

**Comment by nickoe** [comment]
FWIW, it does no make sense to force a port ordering strictly. I mean, sometimes groups of pins is better grouped, but the numbers might not align up properly. But I guess if you have a stretch of GPIO pins or similar not so different pins, you should try to order dem CCW for example.

**Comment by jkriege2** [comment]
that's how I understand the rule ... I wouldn't enforce it only for the sake of the rule ... really has to make sense in the actual case ;-)

**Comment by JoanTheSpark** [comment]
If the CCW rule has got such a low priority I would make that clear in the pictures though (grey color for it's bubble & text like the NC pins maybe?).

Anyhow, good work!

**Comment by jkriege2** [comment]
I updated the image on the CCW-rule (which was removed anyways):
![klc_boxsymbol2](https://cloud.githubusercontent.com/assets/11967523/22402792/5c441f00-e603-11e6-8114-8e11e8423cce.png)

**Comment by pointhi** [comment]
@jkriege2 

I think the pin length on your image is 150mil, not 50mil (the text size should be 50mil)

What about doing a left align of reference and value for symbols like ic's, and matching the left start point of those references. (Note: Those references are not static, but can increase in size, and such behaviour would prevent overlap of references and pins near it)

Like:

![reference](https://cloud.githubusercontent.com/assets/1652144/22403675/0c042c80-e61f-11e6-938b-174c74fa573a.png)

It's only a proposal, but it would be good to create a "perfect" example symbol :)

Thanks for creating such greate images, which should help newbies quite a bit.

**Comment by sujitth** [comment]
Hi,
is there any rules about the Pin name position offset?

![image](https://cloud.githubusercontent.com/assets/6084883/22403781/ee5541aa-e647-11e6-8181-64e5b6528b5f.png)

a value of 15 or 20 will be comfortable for symbols which having internal drawings.

Thanks for the great reference image.

Best Regards,

Sujith

**Comment by SchrodingersGat** [comment]
Jan,

This is some fine work. Having images will really help users to understand the KLC.

I have started to add some of these to the updated [KLC](https://github.com/SchrodingersGat/kicad-library/wiki/KLC). Refer to 3.10 / 3.12 / 8 / 9 for instances of how I think they should be integrated.

Images are placed in "down-down" boxes. This works on Chrome really well. Can we get some testing on other browsers too? e.g.

![popdown](https://cloud.githubusercontent.com/assets/10080325/22403857/a61526e0-e678-11e6-911a-e613622a5590.png)

I also have some suggestions as to visual style for the images:

## Multiple Rules
Some of the images cover too many rules at once (is confusing!) Some can (should) be split into separate images, one for each rule.
However, some may work better as addressing multiple rules in the same image. For this, I would suggest that each callout contains the number of the associated rule. e.g.
![6d1b8372-d4bf-11e6-8f79-799d057c721c](https://cloud.githubusercontent.com/assets/10080325/22403886/0d17ed0a-e679-11e6-9a8d-95825b13fae0.png)

**Comment by jkriege2** [comment]
Hi! I'll work a bit on the images ... I just checked the way you included them ... hhmmm ... the problem (at least on firefox) for me is that it is absolutely not obvious that you can open thise things up ... wouldn't it be possible to simply have the image-thumbnail floating on the right (e.g. as on Wikipedia)

JAN

**Comment by jkriege2** [comment]
# Image for KLC 8.2
![klc_8_2](https://cloud.githubusercontent.com/assets/11967523/22404919/baada2be-e63a-11e6-9a61-d82315fc833b.png)

**Comment by jkriege2** [comment]
# Image for KLC 9.2+9.3
![klc_9_2 3](https://cloud.githubusercontent.com/assets/11967523/22404918/baac43ce-e63a-11e6-86ea-84d1da38e539.png)

**Comment by jkriege2** [comment]
# image for KLC 7.3 and 7.4
![klc_7_3_4](https://cloud.githubusercontent.com/assets/11967523/22405012/236d1108-e63c-11e6-9fc8-69094204fbbb.png)

# image for KLC 7.5 and 7.6
![klc_7_5_6](https://cloud.githubusercontent.com/assets/11967523/22405071/02b7c628-e63d-11e6-8ba6-7579dc756858.png)

**Comment by jkriege2** [comment]
# Image for KLC 3.x
![klc_3](https://cloud.githubusercontent.com/assets/11967523/22405352/85a8b250-e641-11e6-86bb-b5e75cd77ceb.png)

**Comment by jkriege2** [comment]
## Another image for KLC 3.x
![klc_3_v2](https://cloud.githubusercontent.com/assets/11967523/22405429/be3df368-e642-11e6-9a0e-ea194054a0e0.png)

**Comment by jkriege2** [comment]
## Annotated image for KLC 10 (and 9.1)
![klc_10](https://cloud.githubusercontent.com/assets/11967523/22405466/850b128c-e643-11e6-86dc-951c6f17900a.png)

**Comment by jkriege2** [comment]
## Annotated image for KLC 10.x and 8.1 (SMD)
![klc_10_smd](https://cloud.githubusercontent.com/assets/11967523/22405484/d96bb692-e643-11e6-8755-11470497f391.png)

**Comment by jkriege2** [comment]
## Image for SMD components
![klc_7_3_4_smd](https://cloud.githubusercontent.com/assets/11967523/22405545/cafd0006-e644-11e6-85e3-b600c860cfad.png)

**Comment by CarlPoirier** [comment]
Hi @jkriege2,

These are great. May I ask with what program you did them? It would be great to commit the sources to allow modifications further down the road.

**Comment by jkriege2** [comment]
Hi1

I used http://getgreenshot.org/ which is a really nice screenshot tool that allows these annotations. I can provide these files (just how to share them)? I cold upload them to my webpage and post a link, or I simply upload them somehwere to the repos when we#re done1

JAN

**Comment by SchrodingersGat** [comment]
Ok I have added these images (inline, now - https://github.com/SchrodingersGat/kicad-library/wiki/KLC). 

Another option is to just link them:

[Example Image](https://cloud.githubusercontent.com/assets/11967523/22405545/cafd0006-e644-11e6-85e3-b600c860cfad.png)

What do people think? The drop-down box only really works in Chrome so that's not really an option.

**Comment by jkriege2** [comment]
Hi!

I like it if they are inside the text (if thumbnails are not possible ...)

I made a PR to have the images in the repo, so you can link against them without having to rely on the githubcontent.com ...

https://github.com/KiCad/kicad-library/pull/961

Please merge if you think that's a good solution. the .greenshot files are also there so one can still edit the text labels ...

Best,
JAN

**Comment by SchrodingersGat** [comment]
Turns out that you can just use raw HTML so now there are thumbnails - https://github.com/SchrodingersGat/kicad-library/wiki/KLC

**Comment by poeschlr** [comment]
The screenshots using the dip 8 package are missing the pin 1 marker on silk.

Both the smd and tht screenshot miss the reference on the fab layer.

**Comment by SchrodingersGat** [comment]
Thanks for these images :)
