### ISSUE TITLE
Issue with PWR_FLAG and recently added MALE and FEMALE connectors

### ISSUE THREAD

**Issue by cvgaviao** [KiCad/kicad-library#946]
Today I was drawing a schematic with the nightly kicad and found the CONN_01X04_MALE.
I found this new item interesting and used it.
The problem is that those new item uses BIDIRECTIONAL ports instead PASSIVE (from others), 
so I can't use GND or power into those pins.
If I don't add aPWR_FLAG I receive a non driven error, but if I add the PWR_FLAG I receive a conflict error.

**Comment by jkriege2** [comment]
I adressed this in this PR: https://github.com/KiCad/kicad-library/pull/949

**Comment by cvgaviao** [comment]
ok, thanks
