### ISSUE TITLE
Case sensitivity - Windows

### ISSUE THREAD

**Issue by MrMartinZockt** [KiCad/kicad-library#984]
There are two libraries called NXP. One in uppercase and one in lowercase.
But Windows has a case insensitive filesystem. So it is not possible to clone the library properly. One file is always missing.

**Comment by SchrodingersGat** [comment]
Thanks for pointing this out @MrMartinZockt . I have deleted NXP.lib/.dcm (upper case). I will merge the components that were in the upper-case lib into the lower-case one.

**Comment by SchrodingersGat** [comment]
Fix is here - https://github.com/KiCad/kicad-library/pull/985

**Comment by jkriege2** [comment]
Done!
Thanks for pointing this out!

**Comment by MrMartinZockt** [comment]
I found another one

[modules/packages3d/unused_3d.3dshapes/device.douille_4mm(black).wrl](https://github.com/MrMartinZockt/kicad-library/blob/master/modules/packages3d/unused_3d.3dshapes/device.douille_4mm(black).wrl)
[modules/packages3d/unused_3d.3dshapes/device.douille_4mm(black).wings](https://github.com/MrMartinZockt/kicad-library/blob/master/modules/packages3d/unused_3d.3dshapes/device.douille_4mm(black).wings)

and 

[modules/packages3d/unused_3d.3dshapes/Device.douille_4mm(black).wrl](https://github.com/MrMartinZockt/kicad-library/blob/master/modules/packages3d/unused_3d.3dshapes/Device.douille_4mm(black).wrl)
[modules/packages3d/unused_3d.3dshapes/Device.douille_4mm(black).wings](https://github.com/MrMartinZockt/kicad-library/blob/master/modules/packages3d/unused_3d.3dshapes/Device.douille_4mm(black).wings)

**Comment by SchrodingersGat** [comment]
Good find! These have been fixed also.

**Comment by MrMartinZockt** [comment]
Thanks!
Everything is working fine now. :+1:
